//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.1008
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppTest.PruebaService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="PruebaService.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CrearPrueba", ReplyAction="http://tempuri.org/IService1/CrearPruebaResponse")]
        long CrearPrueba(Unisangil.CYLTRACK.CYLTRACK_BE.PruebaBE prueba);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ConsultarPruebas", ReplyAction="http://tempuri.org/IService1/ConsultarPruebasResponse")]
        System.Collections.Generic.List<Unisangil.CYLTRACK.CYLTRACK_BE.PruebaBE> ConsultarPruebas(int idPrueba);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ModificarPrueba", ReplyAction="http://tempuri.org/IService1/ModificarPruebaResponse")]
        int ModificarPrueba(Unisangil.CYLTRACK.CYLTRACK_BE.PruebaBE prueba);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : AppTest.PruebaService.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<AppTest.PruebaService.IService1>, AppTest.PruebaService.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public long CrearPrueba(Unisangil.CYLTRACK.CYLTRACK_BE.PruebaBE prueba) {
            return base.Channel.CrearPrueba(prueba);
        }
        
        public System.Collections.Generic.List<Unisangil.CYLTRACK.CYLTRACK_BE.PruebaBE> ConsultarPruebas(int idPrueba) {
            return base.Channel.ConsultarPruebas(idPrueba);
        }
        
        public int ModificarPrueba(Unisangil.CYLTRACK.CYLTRACK_BE.PruebaBE prueba) {
            return base.Channel.ModificarPrueba(prueba);
        }
    }
}
