//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.269
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This code was auto-generated by Microsoft.Silverlight.Phone.ServiceReference, version 3.7.0.0
// 
namespace CYLTRACK_PHONE.RutaService {
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RutaBE", Namespace="http://schemas.datacontract.org/2004/07/Unisangil.CYLTRACK.CYLTRACK_BE")]
    public partial class RutaBE : object, System.ComponentModel.INotifyPropertyChanged {
        
        private CYLTRACK_PHONE.RutaService.CiudadBE CiudadField;
        
        private CYLTRACK_PHONE.RutaService.Ciudad_RutaBE Ciudad_RutaField;
        
        private string Id_RutaField;
        
        private string Nombre_RutaField;
        
        private CYLTRACK_PHONE.RutaService.Ruta_VehiculoBE Ruta_VehiculoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CYLTRACK_PHONE.RutaService.CiudadBE Ciudad {
            get {
                return this.CiudadField;
            }
            set {
                if ((object.ReferenceEquals(this.CiudadField, value) != true)) {
                    this.CiudadField = value;
                    this.RaisePropertyChanged("Ciudad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CYLTRACK_PHONE.RutaService.Ciudad_RutaBE Ciudad_Ruta {
            get {
                return this.Ciudad_RutaField;
            }
            set {
                if ((object.ReferenceEquals(this.Ciudad_RutaField, value) != true)) {
                    this.Ciudad_RutaField = value;
                    this.RaisePropertyChanged("Ciudad_Ruta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Id_Ruta {
            get {
                return this.Id_RutaField;
            }
            set {
                if ((object.ReferenceEquals(this.Id_RutaField, value) != true)) {
                    this.Id_RutaField = value;
                    this.RaisePropertyChanged("Id_Ruta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre_Ruta {
            get {
                return this.Nombre_RutaField;
            }
            set {
                if ((object.ReferenceEquals(this.Nombre_RutaField, value) != true)) {
                    this.Nombre_RutaField = value;
                    this.RaisePropertyChanged("Nombre_Ruta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CYLTRACK_PHONE.RutaService.Ruta_VehiculoBE Ruta_Vehiculo {
            get {
                return this.Ruta_VehiculoField;
            }
            set {
                if ((object.ReferenceEquals(this.Ruta_VehiculoField, value) != true)) {
                    this.Ruta_VehiculoField = value;
                    this.RaisePropertyChanged("Ruta_Vehiculo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CiudadBE", Namespace="http://schemas.datacontract.org/2004/07/Unisangil.CYLTRACK.CYLTRACK_BE")]
    public partial class CiudadBE : object, System.ComponentModel.INotifyPropertyChanged {
        
        private CYLTRACK_PHONE.RutaService.DepartamentoBE DepartamentoField;
        
        private string Id_CiudadField;
        
        private string Nombre_CiudadField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CYLTRACK_PHONE.RutaService.DepartamentoBE Departamento {
            get {
                return this.DepartamentoField;
            }
            set {
                if ((object.ReferenceEquals(this.DepartamentoField, value) != true)) {
                    this.DepartamentoField = value;
                    this.RaisePropertyChanged("Departamento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Id_Ciudad {
            get {
                return this.Id_CiudadField;
            }
            set {
                if ((object.ReferenceEquals(this.Id_CiudadField, value) != true)) {
                    this.Id_CiudadField = value;
                    this.RaisePropertyChanged("Id_Ciudad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre_Ciudad {
            get {
                return this.Nombre_CiudadField;
            }
            set {
                if ((object.ReferenceEquals(this.Nombre_CiudadField, value) != true)) {
                    this.Nombre_CiudadField = value;
                    this.RaisePropertyChanged("Nombre_Ciudad");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Ciudad_RutaBE", Namespace="http://schemas.datacontract.org/2004/07/Unisangil.CYLTRACK.CYLTRACK_BE")]
    public partial class Ciudad_RutaBE : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.Collections.ObjectModel.ObservableCollection<CYLTRACK_PHONE.RutaService.CiudadBE> CiudadField;
        
        private string Id_Ciudad_RutaField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.ObjectModel.ObservableCollection<CYLTRACK_PHONE.RutaService.CiudadBE> Ciudad {
            get {
                return this.CiudadField;
            }
            set {
                if ((object.ReferenceEquals(this.CiudadField, value) != true)) {
                    this.CiudadField = value;
                    this.RaisePropertyChanged("Ciudad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Id_Ciudad_Ruta {
            get {
                return this.Id_Ciudad_RutaField;
            }
            set {
                if ((object.ReferenceEquals(this.Id_Ciudad_RutaField, value) != true)) {
                    this.Id_Ciudad_RutaField = value;
                    this.RaisePropertyChanged("Id_Ciudad_Ruta");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Ruta_VehiculoBE", Namespace="http://schemas.datacontract.org/2004/07/Unisangil.CYLTRACK.CYLTRACK_BE")]
    public partial class Ruta_VehiculoBE : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string EstadoField;
        
        private string Fecha_FinField;
        
        private string Fecha_InicioField;
        
        private string Id_Ruta_VehiculoField;
        
        private System.Collections.ObjectModel.ObservableCollection<CYLTRACK_PHONE.RutaService.VehiculoBE> VehiculoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Estado {
            get {
                return this.EstadoField;
            }
            set {
                if ((object.ReferenceEquals(this.EstadoField, value) != true)) {
                    this.EstadoField = value;
                    this.RaisePropertyChanged("Estado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Fecha_Fin {
            get {
                return this.Fecha_FinField;
            }
            set {
                if ((object.ReferenceEquals(this.Fecha_FinField, value) != true)) {
                    this.Fecha_FinField = value;
                    this.RaisePropertyChanged("Fecha_Fin");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Fecha_Inicio {
            get {
                return this.Fecha_InicioField;
            }
            set {
                if ((object.ReferenceEquals(this.Fecha_InicioField, value) != true)) {
                    this.Fecha_InicioField = value;
                    this.RaisePropertyChanged("Fecha_Inicio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Id_Ruta_Vehiculo {
            get {
                return this.Id_Ruta_VehiculoField;
            }
            set {
                if ((object.ReferenceEquals(this.Id_Ruta_VehiculoField, value) != true)) {
                    this.Id_Ruta_VehiculoField = value;
                    this.RaisePropertyChanged("Id_Ruta_Vehiculo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.ObjectModel.ObservableCollection<CYLTRACK_PHONE.RutaService.VehiculoBE> Vehiculo {
            get {
                return this.VehiculoField;
            }
            set {
                if ((object.ReferenceEquals(this.VehiculoField, value) != true)) {
                    this.VehiculoField = value;
                    this.RaisePropertyChanged("Vehiculo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DepartamentoBE", Namespace="http://schemas.datacontract.org/2004/07/Unisangil.CYLTRACK.CYLTRACK_BE")]
    public partial class DepartamentoBE : object, System.ComponentModel.INotifyPropertyChanged {
        
        private CYLTRACK_PHONE.RutaService.CiudadBE CiudadField;
        
        private string Id_DepartamentoField;
        
        private string Nombre_DepartamentoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CYLTRACK_PHONE.RutaService.CiudadBE Ciudad {
            get {
                return this.CiudadField;
            }
            set {
                if ((object.ReferenceEquals(this.CiudadField, value) != true)) {
                    this.CiudadField = value;
                    this.RaisePropertyChanged("Ciudad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Id_Departamento {
            get {
                return this.Id_DepartamentoField;
            }
            set {
                if ((object.ReferenceEquals(this.Id_DepartamentoField, value) != true)) {
                    this.Id_DepartamentoField = value;
                    this.RaisePropertyChanged("Id_Departamento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre_Departamento {
            get {
                return this.Nombre_DepartamentoField;
            }
            set {
                if ((object.ReferenceEquals(this.Nombre_DepartamentoField, value) != true)) {
                    this.Nombre_DepartamentoField = value;
                    this.RaisePropertyChanged("Nombre_Departamento");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="VehiculoBE", Namespace="http://schemas.datacontract.org/2004/07/Unisangil.CYLTRACK.CYLTRACK_BE")]
    public partial class VehiculoBE : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string Apellido_1_PropField;
        
        private string Apellido_2_PropField;
        
        private string Ced_PropField;
        
        private string ChasisField;
        
        private string CilindrajeField;
        
        private CYLTRACK_PHONE.RutaService.ConductorBE ConductorField;
        
        private CYLTRACK_PHONE.RutaService.Conductor_VehiculoBE Conductor_VehiculoField;
        
        private string EstadoField;
        
        private string Id_VehiculoField;
        
        private string MarcaField;
        
        private string ModeloField;
        
        private string MotorField;
        
        private string Nombres_PropField;
        
        private string PlacaField;
        
        private CYLTRACK_PHONE.RutaService.RutaBE RutaField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Apellido_1_Prop {
            get {
                return this.Apellido_1_PropField;
            }
            set {
                if ((object.ReferenceEquals(this.Apellido_1_PropField, value) != true)) {
                    this.Apellido_1_PropField = value;
                    this.RaisePropertyChanged("Apellido_1_Prop");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Apellido_2_Prop {
            get {
                return this.Apellido_2_PropField;
            }
            set {
                if ((object.ReferenceEquals(this.Apellido_2_PropField, value) != true)) {
                    this.Apellido_2_PropField = value;
                    this.RaisePropertyChanged("Apellido_2_Prop");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Ced_Prop {
            get {
                return this.Ced_PropField;
            }
            set {
                if ((object.ReferenceEquals(this.Ced_PropField, value) != true)) {
                    this.Ced_PropField = value;
                    this.RaisePropertyChanged("Ced_Prop");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Chasis {
            get {
                return this.ChasisField;
            }
            set {
                if ((object.ReferenceEquals(this.ChasisField, value) != true)) {
                    this.ChasisField = value;
                    this.RaisePropertyChanged("Chasis");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Cilindraje {
            get {
                return this.CilindrajeField;
            }
            set {
                if ((object.ReferenceEquals(this.CilindrajeField, value) != true)) {
                    this.CilindrajeField = value;
                    this.RaisePropertyChanged("Cilindraje");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CYLTRACK_PHONE.RutaService.ConductorBE Conductor {
            get {
                return this.ConductorField;
            }
            set {
                if ((object.ReferenceEquals(this.ConductorField, value) != true)) {
                    this.ConductorField = value;
                    this.RaisePropertyChanged("Conductor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CYLTRACK_PHONE.RutaService.Conductor_VehiculoBE Conductor_Vehiculo {
            get {
                return this.Conductor_VehiculoField;
            }
            set {
                if ((object.ReferenceEquals(this.Conductor_VehiculoField, value) != true)) {
                    this.Conductor_VehiculoField = value;
                    this.RaisePropertyChanged("Conductor_Vehiculo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Estado {
            get {
                return this.EstadoField;
            }
            set {
                if ((object.ReferenceEquals(this.EstadoField, value) != true)) {
                    this.EstadoField = value;
                    this.RaisePropertyChanged("Estado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Id_Vehiculo {
            get {
                return this.Id_VehiculoField;
            }
            set {
                if ((object.ReferenceEquals(this.Id_VehiculoField, value) != true)) {
                    this.Id_VehiculoField = value;
                    this.RaisePropertyChanged("Id_Vehiculo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Marca {
            get {
                return this.MarcaField;
            }
            set {
                if ((object.ReferenceEquals(this.MarcaField, value) != true)) {
                    this.MarcaField = value;
                    this.RaisePropertyChanged("Marca");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Modelo {
            get {
                return this.ModeloField;
            }
            set {
                if ((object.ReferenceEquals(this.ModeloField, value) != true)) {
                    this.ModeloField = value;
                    this.RaisePropertyChanged("Modelo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Motor {
            get {
                return this.MotorField;
            }
            set {
                if ((object.ReferenceEquals(this.MotorField, value) != true)) {
                    this.MotorField = value;
                    this.RaisePropertyChanged("Motor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombres_Prop {
            get {
                return this.Nombres_PropField;
            }
            set {
                if ((object.ReferenceEquals(this.Nombres_PropField, value) != true)) {
                    this.Nombres_PropField = value;
                    this.RaisePropertyChanged("Nombres_Prop");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Placa {
            get {
                return this.PlacaField;
            }
            set {
                if ((object.ReferenceEquals(this.PlacaField, value) != true)) {
                    this.PlacaField = value;
                    this.RaisePropertyChanged("Placa");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CYLTRACK_PHONE.RutaService.RutaBE Ruta {
            get {
                return this.RutaField;
            }
            set {
                if ((object.ReferenceEquals(this.RutaField, value) != true)) {
                    this.RutaField = value;
                    this.RaisePropertyChanged("Ruta");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ConductorBE", Namespace="http://schemas.datacontract.org/2004/07/Unisangil.CYLTRACK.CYLTRACK_BE")]
    public partial class ConductorBE : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string Apellido_1Field;
        
        private string Apellido_2Field;
        
        private string CedulaField;
        
        private string DireccionField;
        
        private string Id_ConductorField;
        
        private string Nombres_ConductorField;
        
        private string TelefonoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Apellido_1 {
            get {
                return this.Apellido_1Field;
            }
            set {
                if ((object.ReferenceEquals(this.Apellido_1Field, value) != true)) {
                    this.Apellido_1Field = value;
                    this.RaisePropertyChanged("Apellido_1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Apellido_2 {
            get {
                return this.Apellido_2Field;
            }
            set {
                if ((object.ReferenceEquals(this.Apellido_2Field, value) != true)) {
                    this.Apellido_2Field = value;
                    this.RaisePropertyChanged("Apellido_2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Cedula {
            get {
                return this.CedulaField;
            }
            set {
                if ((object.ReferenceEquals(this.CedulaField, value) != true)) {
                    this.CedulaField = value;
                    this.RaisePropertyChanged("Cedula");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Direccion {
            get {
                return this.DireccionField;
            }
            set {
                if ((object.ReferenceEquals(this.DireccionField, value) != true)) {
                    this.DireccionField = value;
                    this.RaisePropertyChanged("Direccion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Id_Conductor {
            get {
                return this.Id_ConductorField;
            }
            set {
                if ((object.ReferenceEquals(this.Id_ConductorField, value) != true)) {
                    this.Id_ConductorField = value;
                    this.RaisePropertyChanged("Id_Conductor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombres_Conductor {
            get {
                return this.Nombres_ConductorField;
            }
            set {
                if ((object.ReferenceEquals(this.Nombres_ConductorField, value) != true)) {
                    this.Nombres_ConductorField = value;
                    this.RaisePropertyChanged("Nombres_Conductor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Telefono {
            get {
                return this.TelefonoField;
            }
            set {
                if ((object.ReferenceEquals(this.TelefonoField, value) != true)) {
                    this.TelefonoField = value;
                    this.RaisePropertyChanged("Telefono");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Conductor_VehiculoBE", Namespace="http://schemas.datacontract.org/2004/07/Unisangil.CYLTRACK.CYLTRACK_BE")]
    public partial class Conductor_VehiculoBE : object, System.ComponentModel.INotifyPropertyChanged {
        
        private CYLTRACK_PHONE.RutaService.ConductorBE ConductorField;
        
        private System.DateTime Fecha_FinField;
        
        private System.DateTime Fecha_InicioField;
        
        private string Id_Conductor_VehiculoField;
        
        private CYLTRACK_PHONE.RutaService.VehiculoBE VehiculoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CYLTRACK_PHONE.RutaService.ConductorBE Conductor {
            get {
                return this.ConductorField;
            }
            set {
                if ((object.ReferenceEquals(this.ConductorField, value) != true)) {
                    this.ConductorField = value;
                    this.RaisePropertyChanged("Conductor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Fecha_Fin {
            get {
                return this.Fecha_FinField;
            }
            set {
                if ((this.Fecha_FinField.Equals(value) != true)) {
                    this.Fecha_FinField = value;
                    this.RaisePropertyChanged("Fecha_Fin");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Fecha_Inicio {
            get {
                return this.Fecha_InicioField;
            }
            set {
                if ((this.Fecha_InicioField.Equals(value) != true)) {
                    this.Fecha_InicioField = value;
                    this.RaisePropertyChanged("Fecha_Inicio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Id_Conductor_Vehiculo {
            get {
                return this.Id_Conductor_VehiculoField;
            }
            set {
                if ((object.ReferenceEquals(this.Id_Conductor_VehiculoField, value) != true)) {
                    this.Id_Conductor_VehiculoField = value;
                    this.RaisePropertyChanged("Id_Conductor_Vehiculo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CYLTRACK_PHONE.RutaService.VehiculoBE Vehiculo {
            get {
                return this.VehiculoField;
            }
            set {
                if ((object.ReferenceEquals(this.VehiculoField, value) != true)) {
                    this.VehiculoField = value;
                    this.RaisePropertyChanged("Vehiculo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://servicios.cyltrack.com.co/cyltrack/", ConfigurationName="RutaService.IRutaServices")]
    public interface IRutaServices {
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://servicios.cyltrack.com.co/cyltrack/IRutaServices/RegistrarRuta", ReplyAction="http://servicios.cyltrack.com.co/cyltrack/IRutaServices/RegistrarRutaResponse")]
        System.IAsyncResult BeginRegistrarRuta(CYLTRACK_PHONE.RutaService.RutaBE ruta, System.AsyncCallback callback, object asyncState);
        
        string EndRegistrarRuta(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://servicios.cyltrack.com.co/cyltrack/IRutaServices/ModificarRuta", ReplyAction="http://servicios.cyltrack.com.co/cyltrack/IRutaServices/ModificarRutaResponse")]
        System.IAsyncResult BeginModificarRuta(CYLTRACK_PHONE.RutaService.RutaBE ruta, System.AsyncCallback callback, object asyncState);
        
        string EndModificarRuta(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://servicios.cyltrack.com.co/cyltrack/IRutaServices/ConsultarRutaconParametro" +
            "", ReplyAction="http://servicios.cyltrack.com.co/cyltrack/IRutaServices/ConsultarRutaconParametro" +
            "Response")]
        System.IAsyncResult BeginConsultarRutaconParametro(string ruta, System.AsyncCallback callback, object asyncState);
        
        CYLTRACK_PHONE.RutaService.RutaBE EndConsultarRutaconParametro(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://servicios.cyltrack.com.co/cyltrack/IRutaServices/ConsultaDepartamentoyCiud" +
            "ades", ReplyAction="http://servicios.cyltrack.com.co/cyltrack/IRutaServices/ConsultaDepartamentoyCiud" +
            "adesResponse")]
        System.IAsyncResult BeginConsultaDepartamentoyCiudades(System.AsyncCallback callback, object asyncState);
        
        System.Collections.ObjectModel.ObservableCollection<CYLTRACK_PHONE.RutaService.CiudadBE> EndConsultaDepartamentoyCiudades(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://servicios.cyltrack.com.co/cyltrack/IRutaServices/ConsultaExistencia", ReplyAction="http://servicios.cyltrack.com.co/cyltrack/IRutaServices/ConsultaExistenciaRespons" +
            "e")]
        System.IAsyncResult BeginConsultaExistencia(string ruta, System.AsyncCallback callback, object asyncState);
        
        string EndConsultaExistencia(System.IAsyncResult result);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IRutaServicesChannel : CYLTRACK_PHONE.RutaService.IRutaServices, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RegistrarRutaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public RegistrarRutaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public string Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ModificarRutaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public ModificarRutaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public string Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ConsultarRutaconParametroCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public ConsultarRutaconParametroCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public CYLTRACK_PHONE.RutaService.RutaBE Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((CYLTRACK_PHONE.RutaService.RutaBE)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ConsultaDepartamentoyCiudadesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public ConsultaDepartamentoyCiudadesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public System.Collections.ObjectModel.ObservableCollection<CYLTRACK_PHONE.RutaService.CiudadBE> Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((System.Collections.ObjectModel.ObservableCollection<CYLTRACK_PHONE.RutaService.CiudadBE>)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ConsultaExistenciaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public ConsultaExistenciaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public string Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RutaServicesClient : System.ServiceModel.ClientBase<CYLTRACK_PHONE.RutaService.IRutaServices>, CYLTRACK_PHONE.RutaService.IRutaServices {
        
        private BeginOperationDelegate onBeginRegistrarRutaDelegate;
        
        private EndOperationDelegate onEndRegistrarRutaDelegate;
        
        private System.Threading.SendOrPostCallback onRegistrarRutaCompletedDelegate;
        
        private BeginOperationDelegate onBeginModificarRutaDelegate;
        
        private EndOperationDelegate onEndModificarRutaDelegate;
        
        private System.Threading.SendOrPostCallback onModificarRutaCompletedDelegate;
        
        private BeginOperationDelegate onBeginConsultarRutaconParametroDelegate;
        
        private EndOperationDelegate onEndConsultarRutaconParametroDelegate;
        
        private System.Threading.SendOrPostCallback onConsultarRutaconParametroCompletedDelegate;
        
        private BeginOperationDelegate onBeginConsultaDepartamentoyCiudadesDelegate;
        
        private EndOperationDelegate onEndConsultaDepartamentoyCiudadesDelegate;
        
        private System.Threading.SendOrPostCallback onConsultaDepartamentoyCiudadesCompletedDelegate;
        
        private BeginOperationDelegate onBeginConsultaExistenciaDelegate;
        
        private EndOperationDelegate onEndConsultaExistenciaDelegate;
        
        private System.Threading.SendOrPostCallback onConsultaExistenciaCompletedDelegate;
        
        private BeginOperationDelegate onBeginOpenDelegate;
        
        private EndOperationDelegate onEndOpenDelegate;
        
        private System.Threading.SendOrPostCallback onOpenCompletedDelegate;
        
        private BeginOperationDelegate onBeginCloseDelegate;
        
        private EndOperationDelegate onEndCloseDelegate;
        
        private System.Threading.SendOrPostCallback onCloseCompletedDelegate;
        
        public RutaServicesClient() {
        }
        
        public RutaServicesClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public RutaServicesClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RutaServicesClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RutaServicesClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Net.CookieContainer CookieContainer {
            get {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    return httpCookieContainerManager.CookieContainer;
                }
                else {
                    return null;
                }
            }
            set {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    httpCookieContainerManager.CookieContainer = value;
                }
                else {
                    throw new System.InvalidOperationException("Unable to set the CookieContainer. Please make sure the binding contains an HttpC" +
                            "ookieContainerBindingElement.");
                }
            }
        }
        
        public event System.EventHandler<RegistrarRutaCompletedEventArgs> RegistrarRutaCompleted;
        
        public event System.EventHandler<ModificarRutaCompletedEventArgs> ModificarRutaCompleted;
        
        public event System.EventHandler<ConsultarRutaconParametroCompletedEventArgs> ConsultarRutaconParametroCompleted;
        
        public event System.EventHandler<ConsultaDepartamentoyCiudadesCompletedEventArgs> ConsultaDepartamentoyCiudadesCompleted;
        
        public event System.EventHandler<ConsultaExistenciaCompletedEventArgs> ConsultaExistenciaCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> OpenCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> CloseCompleted;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult CYLTRACK_PHONE.RutaService.IRutaServices.BeginRegistrarRuta(CYLTRACK_PHONE.RutaService.RutaBE ruta, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginRegistrarRuta(ruta, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        string CYLTRACK_PHONE.RutaService.IRutaServices.EndRegistrarRuta(System.IAsyncResult result) {
            return base.Channel.EndRegistrarRuta(result);
        }
        
        private System.IAsyncResult OnBeginRegistrarRuta(object[] inValues, System.AsyncCallback callback, object asyncState) {
            CYLTRACK_PHONE.RutaService.RutaBE ruta = ((CYLTRACK_PHONE.RutaService.RutaBE)(inValues[0]));
            return ((CYLTRACK_PHONE.RutaService.IRutaServices)(this)).BeginRegistrarRuta(ruta, callback, asyncState);
        }
        
        private object[] OnEndRegistrarRuta(System.IAsyncResult result) {
            string retVal = ((CYLTRACK_PHONE.RutaService.IRutaServices)(this)).EndRegistrarRuta(result);
            return new object[] {
                    retVal};
        }
        
        private void OnRegistrarRutaCompleted(object state) {
            if ((this.RegistrarRutaCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.RegistrarRutaCompleted(this, new RegistrarRutaCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void RegistrarRutaAsync(CYLTRACK_PHONE.RutaService.RutaBE ruta) {
            this.RegistrarRutaAsync(ruta, null);
        }
        
        public void RegistrarRutaAsync(CYLTRACK_PHONE.RutaService.RutaBE ruta, object userState) {
            if ((this.onBeginRegistrarRutaDelegate == null)) {
                this.onBeginRegistrarRutaDelegate = new BeginOperationDelegate(this.OnBeginRegistrarRuta);
            }
            if ((this.onEndRegistrarRutaDelegate == null)) {
                this.onEndRegistrarRutaDelegate = new EndOperationDelegate(this.OnEndRegistrarRuta);
            }
            if ((this.onRegistrarRutaCompletedDelegate == null)) {
                this.onRegistrarRutaCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnRegistrarRutaCompleted);
            }
            base.InvokeAsync(this.onBeginRegistrarRutaDelegate, new object[] {
                        ruta}, this.onEndRegistrarRutaDelegate, this.onRegistrarRutaCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult CYLTRACK_PHONE.RutaService.IRutaServices.BeginModificarRuta(CYLTRACK_PHONE.RutaService.RutaBE ruta, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginModificarRuta(ruta, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        string CYLTRACK_PHONE.RutaService.IRutaServices.EndModificarRuta(System.IAsyncResult result) {
            return base.Channel.EndModificarRuta(result);
        }
        
        private System.IAsyncResult OnBeginModificarRuta(object[] inValues, System.AsyncCallback callback, object asyncState) {
            CYLTRACK_PHONE.RutaService.RutaBE ruta = ((CYLTRACK_PHONE.RutaService.RutaBE)(inValues[0]));
            return ((CYLTRACK_PHONE.RutaService.IRutaServices)(this)).BeginModificarRuta(ruta, callback, asyncState);
        }
        
        private object[] OnEndModificarRuta(System.IAsyncResult result) {
            string retVal = ((CYLTRACK_PHONE.RutaService.IRutaServices)(this)).EndModificarRuta(result);
            return new object[] {
                    retVal};
        }
        
        private void OnModificarRutaCompleted(object state) {
            if ((this.ModificarRutaCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.ModificarRutaCompleted(this, new ModificarRutaCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void ModificarRutaAsync(CYLTRACK_PHONE.RutaService.RutaBE ruta) {
            this.ModificarRutaAsync(ruta, null);
        }
        
        public void ModificarRutaAsync(CYLTRACK_PHONE.RutaService.RutaBE ruta, object userState) {
            if ((this.onBeginModificarRutaDelegate == null)) {
                this.onBeginModificarRutaDelegate = new BeginOperationDelegate(this.OnBeginModificarRuta);
            }
            if ((this.onEndModificarRutaDelegate == null)) {
                this.onEndModificarRutaDelegate = new EndOperationDelegate(this.OnEndModificarRuta);
            }
            if ((this.onModificarRutaCompletedDelegate == null)) {
                this.onModificarRutaCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnModificarRutaCompleted);
            }
            base.InvokeAsync(this.onBeginModificarRutaDelegate, new object[] {
                        ruta}, this.onEndModificarRutaDelegate, this.onModificarRutaCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult CYLTRACK_PHONE.RutaService.IRutaServices.BeginConsultarRutaconParametro(string ruta, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginConsultarRutaconParametro(ruta, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CYLTRACK_PHONE.RutaService.RutaBE CYLTRACK_PHONE.RutaService.IRutaServices.EndConsultarRutaconParametro(System.IAsyncResult result) {
            return base.Channel.EndConsultarRutaconParametro(result);
        }
        
        private System.IAsyncResult OnBeginConsultarRutaconParametro(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string ruta = ((string)(inValues[0]));
            return ((CYLTRACK_PHONE.RutaService.IRutaServices)(this)).BeginConsultarRutaconParametro(ruta, callback, asyncState);
        }
        
        private object[] OnEndConsultarRutaconParametro(System.IAsyncResult result) {
            CYLTRACK_PHONE.RutaService.RutaBE retVal = ((CYLTRACK_PHONE.RutaService.IRutaServices)(this)).EndConsultarRutaconParametro(result);
            return new object[] {
                    retVal};
        }
        
        private void OnConsultarRutaconParametroCompleted(object state) {
            if ((this.ConsultarRutaconParametroCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.ConsultarRutaconParametroCompleted(this, new ConsultarRutaconParametroCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void ConsultarRutaconParametroAsync(string ruta) {
            this.ConsultarRutaconParametroAsync(ruta, null);
        }
        
        public void ConsultarRutaconParametroAsync(string ruta, object userState) {
            if ((this.onBeginConsultarRutaconParametroDelegate == null)) {
                this.onBeginConsultarRutaconParametroDelegate = new BeginOperationDelegate(this.OnBeginConsultarRutaconParametro);
            }
            if ((this.onEndConsultarRutaconParametroDelegate == null)) {
                this.onEndConsultarRutaconParametroDelegate = new EndOperationDelegate(this.OnEndConsultarRutaconParametro);
            }
            if ((this.onConsultarRutaconParametroCompletedDelegate == null)) {
                this.onConsultarRutaconParametroCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnConsultarRutaconParametroCompleted);
            }
            base.InvokeAsync(this.onBeginConsultarRutaconParametroDelegate, new object[] {
                        ruta}, this.onEndConsultarRutaconParametroDelegate, this.onConsultarRutaconParametroCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult CYLTRACK_PHONE.RutaService.IRutaServices.BeginConsultaDepartamentoyCiudades(System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginConsultaDepartamentoyCiudades(callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Collections.ObjectModel.ObservableCollection<CYLTRACK_PHONE.RutaService.CiudadBE> CYLTRACK_PHONE.RutaService.IRutaServices.EndConsultaDepartamentoyCiudades(System.IAsyncResult result) {
            return base.Channel.EndConsultaDepartamentoyCiudades(result);
        }
        
        private System.IAsyncResult OnBeginConsultaDepartamentoyCiudades(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((CYLTRACK_PHONE.RutaService.IRutaServices)(this)).BeginConsultaDepartamentoyCiudades(callback, asyncState);
        }
        
        private object[] OnEndConsultaDepartamentoyCiudades(System.IAsyncResult result) {
            System.Collections.ObjectModel.ObservableCollection<CYLTRACK_PHONE.RutaService.CiudadBE> retVal = ((CYLTRACK_PHONE.RutaService.IRutaServices)(this)).EndConsultaDepartamentoyCiudades(result);
            return new object[] {
                    retVal};
        }
        
        private void OnConsultaDepartamentoyCiudadesCompleted(object state) {
            if ((this.ConsultaDepartamentoyCiudadesCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.ConsultaDepartamentoyCiudadesCompleted(this, new ConsultaDepartamentoyCiudadesCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void ConsultaDepartamentoyCiudadesAsync() {
            this.ConsultaDepartamentoyCiudadesAsync(null);
        }
        
        public void ConsultaDepartamentoyCiudadesAsync(object userState) {
            if ((this.onBeginConsultaDepartamentoyCiudadesDelegate == null)) {
                this.onBeginConsultaDepartamentoyCiudadesDelegate = new BeginOperationDelegate(this.OnBeginConsultaDepartamentoyCiudades);
            }
            if ((this.onEndConsultaDepartamentoyCiudadesDelegate == null)) {
                this.onEndConsultaDepartamentoyCiudadesDelegate = new EndOperationDelegate(this.OnEndConsultaDepartamentoyCiudades);
            }
            if ((this.onConsultaDepartamentoyCiudadesCompletedDelegate == null)) {
                this.onConsultaDepartamentoyCiudadesCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnConsultaDepartamentoyCiudadesCompleted);
            }
            base.InvokeAsync(this.onBeginConsultaDepartamentoyCiudadesDelegate, null, this.onEndConsultaDepartamentoyCiudadesDelegate, this.onConsultaDepartamentoyCiudadesCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult CYLTRACK_PHONE.RutaService.IRutaServices.BeginConsultaExistencia(string ruta, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginConsultaExistencia(ruta, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        string CYLTRACK_PHONE.RutaService.IRutaServices.EndConsultaExistencia(System.IAsyncResult result) {
            return base.Channel.EndConsultaExistencia(result);
        }
        
        private System.IAsyncResult OnBeginConsultaExistencia(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string ruta = ((string)(inValues[0]));
            return ((CYLTRACK_PHONE.RutaService.IRutaServices)(this)).BeginConsultaExistencia(ruta, callback, asyncState);
        }
        
        private object[] OnEndConsultaExistencia(System.IAsyncResult result) {
            string retVal = ((CYLTRACK_PHONE.RutaService.IRutaServices)(this)).EndConsultaExistencia(result);
            return new object[] {
                    retVal};
        }
        
        private void OnConsultaExistenciaCompleted(object state) {
            if ((this.ConsultaExistenciaCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.ConsultaExistenciaCompleted(this, new ConsultaExistenciaCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void ConsultaExistenciaAsync(string ruta) {
            this.ConsultaExistenciaAsync(ruta, null);
        }
        
        public void ConsultaExistenciaAsync(string ruta, object userState) {
            if ((this.onBeginConsultaExistenciaDelegate == null)) {
                this.onBeginConsultaExistenciaDelegate = new BeginOperationDelegate(this.OnBeginConsultaExistencia);
            }
            if ((this.onEndConsultaExistenciaDelegate == null)) {
                this.onEndConsultaExistenciaDelegate = new EndOperationDelegate(this.OnEndConsultaExistencia);
            }
            if ((this.onConsultaExistenciaCompletedDelegate == null)) {
                this.onConsultaExistenciaCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnConsultaExistenciaCompleted);
            }
            base.InvokeAsync(this.onBeginConsultaExistenciaDelegate, new object[] {
                        ruta}, this.onEndConsultaExistenciaDelegate, this.onConsultaExistenciaCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginOpen(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(callback, asyncState);
        }
        
        private object[] OnEndOpen(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndOpen(result);
            return null;
        }
        
        private void OnOpenCompleted(object state) {
            if ((this.OpenCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.OpenCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void OpenAsync() {
            this.OpenAsync(null);
        }
        
        public void OpenAsync(object userState) {
            if ((this.onBeginOpenDelegate == null)) {
                this.onBeginOpenDelegate = new BeginOperationDelegate(this.OnBeginOpen);
            }
            if ((this.onEndOpenDelegate == null)) {
                this.onEndOpenDelegate = new EndOperationDelegate(this.OnEndOpen);
            }
            if ((this.onOpenCompletedDelegate == null)) {
                this.onOpenCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnOpenCompleted);
            }
            base.InvokeAsync(this.onBeginOpenDelegate, null, this.onEndOpenDelegate, this.onOpenCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginClose(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginClose(callback, asyncState);
        }
        
        private object[] OnEndClose(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndClose(result);
            return null;
        }
        
        private void OnCloseCompleted(object state) {
            if ((this.CloseCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.CloseCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void CloseAsync() {
            this.CloseAsync(null);
        }
        
        public void CloseAsync(object userState) {
            if ((this.onBeginCloseDelegate == null)) {
                this.onBeginCloseDelegate = new BeginOperationDelegate(this.OnBeginClose);
            }
            if ((this.onEndCloseDelegate == null)) {
                this.onEndCloseDelegate = new EndOperationDelegate(this.OnEndClose);
            }
            if ((this.onCloseCompletedDelegate == null)) {
                this.onCloseCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCloseCompleted);
            }
            base.InvokeAsync(this.onBeginCloseDelegate, null, this.onEndCloseDelegate, this.onCloseCompletedDelegate, userState);
        }
        
        protected override CYLTRACK_PHONE.RutaService.IRutaServices CreateChannel() {
            return new RutaServicesClientChannel(this);
        }
        
        private class RutaServicesClientChannel : ChannelBase<CYLTRACK_PHONE.RutaService.IRutaServices>, CYLTRACK_PHONE.RutaService.IRutaServices {
            
            public RutaServicesClientChannel(System.ServiceModel.ClientBase<CYLTRACK_PHONE.RutaService.IRutaServices> client) : 
                    base(client) {
            }
            
            public System.IAsyncResult BeginRegistrarRuta(CYLTRACK_PHONE.RutaService.RutaBE ruta, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = ruta;
                System.IAsyncResult _result = base.BeginInvoke("RegistrarRuta", _args, callback, asyncState);
                return _result;
            }
            
            public string EndRegistrarRuta(System.IAsyncResult result) {
                object[] _args = new object[0];
                string _result = ((string)(base.EndInvoke("RegistrarRuta", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginModificarRuta(CYLTRACK_PHONE.RutaService.RutaBE ruta, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = ruta;
                System.IAsyncResult _result = base.BeginInvoke("ModificarRuta", _args, callback, asyncState);
                return _result;
            }
            
            public string EndModificarRuta(System.IAsyncResult result) {
                object[] _args = new object[0];
                string _result = ((string)(base.EndInvoke("ModificarRuta", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginConsultarRutaconParametro(string ruta, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = ruta;
                System.IAsyncResult _result = base.BeginInvoke("ConsultarRutaconParametro", _args, callback, asyncState);
                return _result;
            }
            
            public CYLTRACK_PHONE.RutaService.RutaBE EndConsultarRutaconParametro(System.IAsyncResult result) {
                object[] _args = new object[0];
                CYLTRACK_PHONE.RutaService.RutaBE _result = ((CYLTRACK_PHONE.RutaService.RutaBE)(base.EndInvoke("ConsultarRutaconParametro", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginConsultaDepartamentoyCiudades(System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[0];
                System.IAsyncResult _result = base.BeginInvoke("ConsultaDepartamentoyCiudades", _args, callback, asyncState);
                return _result;
            }
            
            public System.Collections.ObjectModel.ObservableCollection<CYLTRACK_PHONE.RutaService.CiudadBE> EndConsultaDepartamentoyCiudades(System.IAsyncResult result) {
                object[] _args = new object[0];
                System.Collections.ObjectModel.ObservableCollection<CYLTRACK_PHONE.RutaService.CiudadBE> _result = ((System.Collections.ObjectModel.ObservableCollection<CYLTRACK_PHONE.RutaService.CiudadBE>)(base.EndInvoke("ConsultaDepartamentoyCiudades", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginConsultaExistencia(string ruta, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = ruta;
                System.IAsyncResult _result = base.BeginInvoke("ConsultaExistencia", _args, callback, asyncState);
                return _result;
            }
            
            public string EndConsultaExistencia(System.IAsyncResult result) {
                object[] _args = new object[0];
                string _result = ((string)(base.EndInvoke("ConsultaExistencia", _args, result)));
                return _result;
            }
        }
    }
}
