//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.296
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CYLTRACK_WebApp.VentaService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://servicios.cyltrack.com.co/cyltrack/", ConfigurationName="VentaService.IVentaService")]
    public interface IVentaService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://servicios.cyltrack.com.co/cyltrack/IVentaService/VentaCilindro", ReplyAction="http://servicios.cyltrack.com.co/cyltrack/IVentaService/VentaCilindroResponse")]
        string VentaCilindro(Unisangil.CYLTRACK.CYLTRACK_BE.VentaBE ventas);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://servicios.cyltrack.com.co/cyltrack/IVentaService/ConsultarVenta", ReplyAction="http://servicios.cyltrack.com.co/cyltrack/IVentaService/ConsultarVentaResponse")]
        Unisangil.CYLTRACK.CYLTRACK_BE.VentaBE[] ConsultarVenta(Unisangil.CYLTRACK.CYLTRACK_BE.VentaBE ventas);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://servicios.cyltrack.com.co/cyltrack/IVentaService/RevisionCasosEspeciales", ReplyAction="http://servicios.cyltrack.com.co/cyltrack/IVentaService/RevisionCasosEspecialesRe" +
            "sponse")]
        Unisangil.CYLTRACK.CYLTRACK_BE.CasosBE[] RevisionCasosEspeciales(Unisangil.CYLTRACK.CYLTRACK_BE.CasosBE casos);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://servicios.cyltrack.com.co/cyltrack/IVentaService/CasosEspeciales", ReplyAction="http://servicios.cyltrack.com.co/cyltrack/IVentaService/CasosEspecialesResponse")]
        string CasosEspeciales(Unisangil.CYLTRACK.CYLTRACK_BE.VentaBE ventas);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IVentaServiceChannel : CYLTRACK_WebApp.VentaService.IVentaService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class VentaServiceClient : System.ServiceModel.ClientBase<CYLTRACK_WebApp.VentaService.IVentaService>, CYLTRACK_WebApp.VentaService.IVentaService {
        
        public VentaServiceClient() {
        }
        
        public VentaServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public VentaServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public VentaServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public VentaServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string VentaCilindro(Unisangil.CYLTRACK.CYLTRACK_BE.VentaBE ventas) {
            return base.Channel.VentaCilindro(ventas);
        }
        
        public Unisangil.CYLTRACK.CYLTRACK_BE.VentaBE[] ConsultarVenta(Unisangil.CYLTRACK.CYLTRACK_BE.VentaBE ventas) {
            return base.Channel.ConsultarVenta(ventas);
        }
        
        public Unisangil.CYLTRACK.CYLTRACK_BE.CasosBE[] RevisionCasosEspeciales(Unisangil.CYLTRACK.CYLTRACK_BE.CasosBE casos) {
            return base.Channel.RevisionCasosEspeciales(casos);
        }
        
        public string CasosEspeciales(Unisangil.CYLTRACK.CYLTRACK_BE.VentaBE ventas) {
            return base.Channel.CasosEspeciales(ventas);
        }
    }
}
