//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.269
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This code was auto-generated by Microsoft.Silverlight.Phone.ServiceReference, version 3.7.0.0
// 
namespace CYLTRACK_PHONE.VehiculoService {
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="VehiculoBE", Namespace="http://schemas.datacontract.org/2004/07/Unisangil.CYLTRACK.CYLTRACK_BE")]
    public partial class VehiculoBE : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string Apellido_1_PropField;
        
        private string Apellido_2_PropField;
        
        private string Ced_PropField;
        
        private string ChasisField;
        
        private string CilindrajeField;
        
        private CYLTRACK_PHONE.VehiculoService.ConductorBE ConductorField;
        
        private CYLTRACK_PHONE.VehiculoService.Conductor_VehiculoBE Conductor_VehiculoField;
        
        private string EstadoField;
        
        private string Id_VehiculoField;
        
        private string MarcaField;
        
        private string ModeloField;
        
        private string MotorField;
        
        private string Nombres_PropField;
        
        private string PlacaField;
        
        private CYLTRACK_PHONE.VehiculoService.RutaBE RutaField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Apellido_1_Prop {
            get {
                return this.Apellido_1_PropField;
            }
            set {
                if ((object.ReferenceEquals(this.Apellido_1_PropField, value) != true)) {
                    this.Apellido_1_PropField = value;
                    this.RaisePropertyChanged("Apellido_1_Prop");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Apellido_2_Prop {
            get {
                return this.Apellido_2_PropField;
            }
            set {
                if ((object.ReferenceEquals(this.Apellido_2_PropField, value) != true)) {
                    this.Apellido_2_PropField = value;
                    this.RaisePropertyChanged("Apellido_2_Prop");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Ced_Prop {
            get {
                return this.Ced_PropField;
            }
            set {
                if ((object.ReferenceEquals(this.Ced_PropField, value) != true)) {
                    this.Ced_PropField = value;
                    this.RaisePropertyChanged("Ced_Prop");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Chasis {
            get {
                return this.ChasisField;
            }
            set {
                if ((object.ReferenceEquals(this.ChasisField, value) != true)) {
                    this.ChasisField = value;
                    this.RaisePropertyChanged("Chasis");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Cilindraje {
            get {
                return this.CilindrajeField;
            }
            set {
                if ((object.ReferenceEquals(this.CilindrajeField, value) != true)) {
                    this.CilindrajeField = value;
                    this.RaisePropertyChanged("Cilindraje");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CYLTRACK_PHONE.VehiculoService.ConductorBE Conductor {
            get {
                return this.ConductorField;
            }
            set {
                if ((object.ReferenceEquals(this.ConductorField, value) != true)) {
                    this.ConductorField = value;
                    this.RaisePropertyChanged("Conductor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CYLTRACK_PHONE.VehiculoService.Conductor_VehiculoBE Conductor_Vehiculo {
            get {
                return this.Conductor_VehiculoField;
            }
            set {
                if ((object.ReferenceEquals(this.Conductor_VehiculoField, value) != true)) {
                    this.Conductor_VehiculoField = value;
                    this.RaisePropertyChanged("Conductor_Vehiculo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Estado {
            get {
                return this.EstadoField;
            }
            set {
                if ((object.ReferenceEquals(this.EstadoField, value) != true)) {
                    this.EstadoField = value;
                    this.RaisePropertyChanged("Estado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Id_Vehiculo {
            get {
                return this.Id_VehiculoField;
            }
            set {
                if ((object.ReferenceEquals(this.Id_VehiculoField, value) != true)) {
                    this.Id_VehiculoField = value;
                    this.RaisePropertyChanged("Id_Vehiculo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Marca {
            get {
                return this.MarcaField;
            }
            set {
                if ((object.ReferenceEquals(this.MarcaField, value) != true)) {
                    this.MarcaField = value;
                    this.RaisePropertyChanged("Marca");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Modelo {
            get {
                return this.ModeloField;
            }
            set {
                if ((object.ReferenceEquals(this.ModeloField, value) != true)) {
                    this.ModeloField = value;
                    this.RaisePropertyChanged("Modelo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Motor {
            get {
                return this.MotorField;
            }
            set {
                if ((object.ReferenceEquals(this.MotorField, value) != true)) {
                    this.MotorField = value;
                    this.RaisePropertyChanged("Motor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombres_Prop {
            get {
                return this.Nombres_PropField;
            }
            set {
                if ((object.ReferenceEquals(this.Nombres_PropField, value) != true)) {
                    this.Nombres_PropField = value;
                    this.RaisePropertyChanged("Nombres_Prop");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Placa {
            get {
                return this.PlacaField;
            }
            set {
                if ((object.ReferenceEquals(this.PlacaField, value) != true)) {
                    this.PlacaField = value;
                    this.RaisePropertyChanged("Placa");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CYLTRACK_PHONE.VehiculoService.RutaBE Ruta {
            get {
                return this.RutaField;
            }
            set {
                if ((object.ReferenceEquals(this.RutaField, value) != true)) {
                    this.RutaField = value;
                    this.RaisePropertyChanged("Ruta");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ConductorBE", Namespace="http://schemas.datacontract.org/2004/07/Unisangil.CYLTRACK.CYLTRACK_BE")]
    public partial class ConductorBE : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string Apellido_1Field;
        
        private string Apellido_2Field;
        
        private string CedulaField;
        
        private string DireccionField;
        
        private string Id_ConductorField;
        
        private string Nombres_ConductorField;
        
        private string TelefonoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Apellido_1 {
            get {
                return this.Apellido_1Field;
            }
            set {
                if ((object.ReferenceEquals(this.Apellido_1Field, value) != true)) {
                    this.Apellido_1Field = value;
                    this.RaisePropertyChanged("Apellido_1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Apellido_2 {
            get {
                return this.Apellido_2Field;
            }
            set {
                if ((object.ReferenceEquals(this.Apellido_2Field, value) != true)) {
                    this.Apellido_2Field = value;
                    this.RaisePropertyChanged("Apellido_2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Cedula {
            get {
                return this.CedulaField;
            }
            set {
                if ((object.ReferenceEquals(this.CedulaField, value) != true)) {
                    this.CedulaField = value;
                    this.RaisePropertyChanged("Cedula");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Direccion {
            get {
                return this.DireccionField;
            }
            set {
                if ((object.ReferenceEquals(this.DireccionField, value) != true)) {
                    this.DireccionField = value;
                    this.RaisePropertyChanged("Direccion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Id_Conductor {
            get {
                return this.Id_ConductorField;
            }
            set {
                if ((object.ReferenceEquals(this.Id_ConductorField, value) != true)) {
                    this.Id_ConductorField = value;
                    this.RaisePropertyChanged("Id_Conductor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombres_Conductor {
            get {
                return this.Nombres_ConductorField;
            }
            set {
                if ((object.ReferenceEquals(this.Nombres_ConductorField, value) != true)) {
                    this.Nombres_ConductorField = value;
                    this.RaisePropertyChanged("Nombres_Conductor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Telefono {
            get {
                return this.TelefonoField;
            }
            set {
                if ((object.ReferenceEquals(this.TelefonoField, value) != true)) {
                    this.TelefonoField = value;
                    this.RaisePropertyChanged("Telefono");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Conductor_VehiculoBE", Namespace="http://schemas.datacontract.org/2004/07/Unisangil.CYLTRACK.CYLTRACK_BE")]
    public partial class Conductor_VehiculoBE : object, System.ComponentModel.INotifyPropertyChanged {
        
        private CYLTRACK_PHONE.VehiculoService.ConductorBE ConductorField;
        
        private System.DateTime Fecha_FinField;
        
        private System.DateTime Fecha_InicioField;
        
        private string Id_Conductor_VehiculoField;
        
        private CYLTRACK_PHONE.VehiculoService.VehiculoBE VehiculoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CYLTRACK_PHONE.VehiculoService.ConductorBE Conductor {
            get {
                return this.ConductorField;
            }
            set {
                if ((object.ReferenceEquals(this.ConductorField, value) != true)) {
                    this.ConductorField = value;
                    this.RaisePropertyChanged("Conductor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Fecha_Fin {
            get {
                return this.Fecha_FinField;
            }
            set {
                if ((this.Fecha_FinField.Equals(value) != true)) {
                    this.Fecha_FinField = value;
                    this.RaisePropertyChanged("Fecha_Fin");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Fecha_Inicio {
            get {
                return this.Fecha_InicioField;
            }
            set {
                if ((this.Fecha_InicioField.Equals(value) != true)) {
                    this.Fecha_InicioField = value;
                    this.RaisePropertyChanged("Fecha_Inicio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Id_Conductor_Vehiculo {
            get {
                return this.Id_Conductor_VehiculoField;
            }
            set {
                if ((object.ReferenceEquals(this.Id_Conductor_VehiculoField, value) != true)) {
                    this.Id_Conductor_VehiculoField = value;
                    this.RaisePropertyChanged("Id_Conductor_Vehiculo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CYLTRACK_PHONE.VehiculoService.VehiculoBE Vehiculo {
            get {
                return this.VehiculoField;
            }
            set {
                if ((object.ReferenceEquals(this.VehiculoField, value) != true)) {
                    this.VehiculoField = value;
                    this.RaisePropertyChanged("Vehiculo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RutaBE", Namespace="http://schemas.datacontract.org/2004/07/Unisangil.CYLTRACK.CYLTRACK_BE")]
    public partial class RutaBE : object, System.ComponentModel.INotifyPropertyChanged {
        
        private CYLTRACK_PHONE.VehiculoService.CiudadBE CiudadField;
        
        private CYLTRACK_PHONE.VehiculoService.Ciudad_RutaBE Ciudad_RutaField;
        
        private string Id_RutaField;
        
        private string Nombre_RutaField;
        
        private CYLTRACK_PHONE.VehiculoService.Ruta_VehiculoBE Ruta_VehiculoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CYLTRACK_PHONE.VehiculoService.CiudadBE Ciudad {
            get {
                return this.CiudadField;
            }
            set {
                if ((object.ReferenceEquals(this.CiudadField, value) != true)) {
                    this.CiudadField = value;
                    this.RaisePropertyChanged("Ciudad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CYLTRACK_PHONE.VehiculoService.Ciudad_RutaBE Ciudad_Ruta {
            get {
                return this.Ciudad_RutaField;
            }
            set {
                if ((object.ReferenceEquals(this.Ciudad_RutaField, value) != true)) {
                    this.Ciudad_RutaField = value;
                    this.RaisePropertyChanged("Ciudad_Ruta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Id_Ruta {
            get {
                return this.Id_RutaField;
            }
            set {
                if ((object.ReferenceEquals(this.Id_RutaField, value) != true)) {
                    this.Id_RutaField = value;
                    this.RaisePropertyChanged("Id_Ruta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre_Ruta {
            get {
                return this.Nombre_RutaField;
            }
            set {
                if ((object.ReferenceEquals(this.Nombre_RutaField, value) != true)) {
                    this.Nombre_RutaField = value;
                    this.RaisePropertyChanged("Nombre_Ruta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CYLTRACK_PHONE.VehiculoService.Ruta_VehiculoBE Ruta_Vehiculo {
            get {
                return this.Ruta_VehiculoField;
            }
            set {
                if ((object.ReferenceEquals(this.Ruta_VehiculoField, value) != true)) {
                    this.Ruta_VehiculoField = value;
                    this.RaisePropertyChanged("Ruta_Vehiculo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CiudadBE", Namespace="http://schemas.datacontract.org/2004/07/Unisangil.CYLTRACK.CYLTRACK_BE")]
    public partial class CiudadBE : object, System.ComponentModel.INotifyPropertyChanged {
        
        private CYLTRACK_PHONE.VehiculoService.DepartamentoBE DepartamentoField;
        
        private string Id_CiudadField;
        
        private string Nombre_CiudadField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CYLTRACK_PHONE.VehiculoService.DepartamentoBE Departamento {
            get {
                return this.DepartamentoField;
            }
            set {
                if ((object.ReferenceEquals(this.DepartamentoField, value) != true)) {
                    this.DepartamentoField = value;
                    this.RaisePropertyChanged("Departamento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Id_Ciudad {
            get {
                return this.Id_CiudadField;
            }
            set {
                if ((object.ReferenceEquals(this.Id_CiudadField, value) != true)) {
                    this.Id_CiudadField = value;
                    this.RaisePropertyChanged("Id_Ciudad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre_Ciudad {
            get {
                return this.Nombre_CiudadField;
            }
            set {
                if ((object.ReferenceEquals(this.Nombre_CiudadField, value) != true)) {
                    this.Nombre_CiudadField = value;
                    this.RaisePropertyChanged("Nombre_Ciudad");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Ciudad_RutaBE", Namespace="http://schemas.datacontract.org/2004/07/Unisangil.CYLTRACK.CYLTRACK_BE")]
    public partial class Ciudad_RutaBE : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.Collections.ObjectModel.ObservableCollection<CYLTRACK_PHONE.VehiculoService.CiudadBE> CiudadField;
        
        private string Id_Ciudad_RutaField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.ObjectModel.ObservableCollection<CYLTRACK_PHONE.VehiculoService.CiudadBE> Ciudad {
            get {
                return this.CiudadField;
            }
            set {
                if ((object.ReferenceEquals(this.CiudadField, value) != true)) {
                    this.CiudadField = value;
                    this.RaisePropertyChanged("Ciudad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Id_Ciudad_Ruta {
            get {
                return this.Id_Ciudad_RutaField;
            }
            set {
                if ((object.ReferenceEquals(this.Id_Ciudad_RutaField, value) != true)) {
                    this.Id_Ciudad_RutaField = value;
                    this.RaisePropertyChanged("Id_Ciudad_Ruta");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Ruta_VehiculoBE", Namespace="http://schemas.datacontract.org/2004/07/Unisangil.CYLTRACK.CYLTRACK_BE")]
    public partial class Ruta_VehiculoBE : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string EstadoField;
        
        private string Fecha_FinField;
        
        private string Fecha_InicioField;
        
        private string Id_Ruta_VehiculoField;
        
        private System.Collections.ObjectModel.ObservableCollection<CYLTRACK_PHONE.VehiculoService.VehiculoBE> VehiculoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Estado {
            get {
                return this.EstadoField;
            }
            set {
                if ((object.ReferenceEquals(this.EstadoField, value) != true)) {
                    this.EstadoField = value;
                    this.RaisePropertyChanged("Estado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Fecha_Fin {
            get {
                return this.Fecha_FinField;
            }
            set {
                if ((object.ReferenceEquals(this.Fecha_FinField, value) != true)) {
                    this.Fecha_FinField = value;
                    this.RaisePropertyChanged("Fecha_Fin");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Fecha_Inicio {
            get {
                return this.Fecha_InicioField;
            }
            set {
                if ((object.ReferenceEquals(this.Fecha_InicioField, value) != true)) {
                    this.Fecha_InicioField = value;
                    this.RaisePropertyChanged("Fecha_Inicio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Id_Ruta_Vehiculo {
            get {
                return this.Id_Ruta_VehiculoField;
            }
            set {
                if ((object.ReferenceEquals(this.Id_Ruta_VehiculoField, value) != true)) {
                    this.Id_Ruta_VehiculoField = value;
                    this.RaisePropertyChanged("Id_Ruta_Vehiculo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.ObjectModel.ObservableCollection<CYLTRACK_PHONE.VehiculoService.VehiculoBE> Vehiculo {
            get {
                return this.VehiculoField;
            }
            set {
                if ((object.ReferenceEquals(this.VehiculoField, value) != true)) {
                    this.VehiculoField = value;
                    this.RaisePropertyChanged("Vehiculo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DepartamentoBE", Namespace="http://schemas.datacontract.org/2004/07/Unisangil.CYLTRACK.CYLTRACK_BE")]
    public partial class DepartamentoBE : object, System.ComponentModel.INotifyPropertyChanged {
        
        private CYLTRACK_PHONE.VehiculoService.CiudadBE CiudadField;
        
        private string Id_DepartamentoField;
        
        private string Nombre_DepartamentoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CYLTRACK_PHONE.VehiculoService.CiudadBE Ciudad {
            get {
                return this.CiudadField;
            }
            set {
                if ((object.ReferenceEquals(this.CiudadField, value) != true)) {
                    this.CiudadField = value;
                    this.RaisePropertyChanged("Ciudad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Id_Departamento {
            get {
                return this.Id_DepartamentoField;
            }
            set {
                if ((object.ReferenceEquals(this.Id_DepartamentoField, value) != true)) {
                    this.Id_DepartamentoField = value;
                    this.RaisePropertyChanged("Id_Departamento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre_Departamento {
            get {
                return this.Nombre_DepartamentoField;
            }
            set {
                if ((object.ReferenceEquals(this.Nombre_DepartamentoField, value) != true)) {
                    this.Nombre_DepartamentoField = value;
                    this.RaisePropertyChanged("Nombre_Departamento");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://servicios.cyltrack.com.co/cyltrack/", ConfigurationName="VehiculoService.IVehiculoService")]
    public interface IVehiculoService {
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://servicios.cyltrack.com.co/cyltrack/IVehiculoService/Registrar_Vehiculo", ReplyAction="http://servicios.cyltrack.com.co/cyltrack/IVehiculoService/Registrar_VehiculoResp" +
            "onse")]
        System.IAsyncResult BeginRegistrar_Vehiculo(CYLTRACK_PHONE.VehiculoService.VehiculoBE vehiculo, System.AsyncCallback callback, object asyncState);
        
        string EndRegistrar_Vehiculo(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://servicios.cyltrack.com.co/cyltrack/IVehiculoService/Consultar_Vehiculo", ReplyAction="http://servicios.cyltrack.com.co/cyltrack/IVehiculoService/Consultar_VehiculoResp" +
            "onse")]
        System.IAsyncResult BeginConsultar_Vehiculo(string vehiculo, System.AsyncCallback callback, object asyncState);
        
        CYLTRACK_PHONE.VehiculoService.VehiculoBE EndConsultar_Vehiculo(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://servicios.cyltrack.com.co/cyltrack/IVehiculoService/Consultar_Existencia", ReplyAction="http://servicios.cyltrack.com.co/cyltrack/IVehiculoService/Consultar_ExistenciaRe" +
            "sponse")]
        System.IAsyncResult BeginConsultar_Existencia(string consultar_existencia, System.AsyncCallback callback, object asyncState);
        
        string EndConsultar_Existencia(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://servicios.cyltrack.com.co/cyltrack/IVehiculoService/Modificar_Vehiculo", ReplyAction="http://servicios.cyltrack.com.co/cyltrack/IVehiculoService/Modificar_VehiculoResp" +
            "onse")]
        System.IAsyncResult BeginModificar_Vehiculo(string vehiculo, System.AsyncCallback callback, object asyncState);
        
        string EndModificar_Vehiculo(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://servicios.cyltrack.com.co/cyltrack/IVehiculoService/Consultar_Conductor", ReplyAction="http://servicios.cyltrack.com.co/cyltrack/IVehiculoService/Consultar_ConductorRes" +
            "ponse")]
        System.IAsyncResult BeginConsultar_Conductor(string conductor, System.AsyncCallback callback, object asyncState);
        
        CYLTRACK_PHONE.VehiculoService.VehiculoBE EndConsultar_Conductor(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://servicios.cyltrack.com.co/cyltrack/IVehiculoService/ConsultarPlacaSinParam" +
            "etro", ReplyAction="http://servicios.cyltrack.com.co/cyltrack/IVehiculoService/ConsultarPlacaSinParam" +
            "etroResponse")]
        System.IAsyncResult BeginConsultarPlacaSinParametro(System.AsyncCallback callback, object asyncState);
        
        System.Collections.ObjectModel.ObservableCollection<string> EndConsultarPlacaSinParametro(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://servicios.cyltrack.com.co/cyltrack/IVehiculoService/ConsultarPlaca", ReplyAction="http://servicios.cyltrack.com.co/cyltrack/IVehiculoService/ConsultarPlacaResponse" +
            "")]
        System.IAsyncResult BeginConsultarPlaca(string ciudad, System.AsyncCallback callback, object asyncState);
        
        System.Collections.ObjectModel.ObservableCollection<string> EndConsultarPlaca(System.IAsyncResult result);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IVehiculoServiceChannel : CYLTRACK_PHONE.VehiculoService.IVehiculoService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Registrar_VehiculoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public Registrar_VehiculoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public string Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Consultar_VehiculoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public Consultar_VehiculoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public CYLTRACK_PHONE.VehiculoService.VehiculoBE Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((CYLTRACK_PHONE.VehiculoService.VehiculoBE)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Consultar_ExistenciaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public Consultar_ExistenciaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public string Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Modificar_VehiculoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public Modificar_VehiculoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public string Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Consultar_ConductorCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public Consultar_ConductorCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public CYLTRACK_PHONE.VehiculoService.VehiculoBE Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((CYLTRACK_PHONE.VehiculoService.VehiculoBE)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ConsultarPlacaSinParametroCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public ConsultarPlacaSinParametroCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public System.Collections.ObjectModel.ObservableCollection<string> Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((System.Collections.ObjectModel.ObservableCollection<string>)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ConsultarPlacaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public ConsultarPlacaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public System.Collections.ObjectModel.ObservableCollection<string> Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((System.Collections.ObjectModel.ObservableCollection<string>)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class VehiculoServiceClient : System.ServiceModel.ClientBase<CYLTRACK_PHONE.VehiculoService.IVehiculoService>, CYLTRACK_PHONE.VehiculoService.IVehiculoService {
        
        private BeginOperationDelegate onBeginRegistrar_VehiculoDelegate;
        
        private EndOperationDelegate onEndRegistrar_VehiculoDelegate;
        
        private System.Threading.SendOrPostCallback onRegistrar_VehiculoCompletedDelegate;
        
        private BeginOperationDelegate onBeginConsultar_VehiculoDelegate;
        
        private EndOperationDelegate onEndConsultar_VehiculoDelegate;
        
        private System.Threading.SendOrPostCallback onConsultar_VehiculoCompletedDelegate;
        
        private BeginOperationDelegate onBeginConsultar_ExistenciaDelegate;
        
        private EndOperationDelegate onEndConsultar_ExistenciaDelegate;
        
        private System.Threading.SendOrPostCallback onConsultar_ExistenciaCompletedDelegate;
        
        private BeginOperationDelegate onBeginModificar_VehiculoDelegate;
        
        private EndOperationDelegate onEndModificar_VehiculoDelegate;
        
        private System.Threading.SendOrPostCallback onModificar_VehiculoCompletedDelegate;
        
        private BeginOperationDelegate onBeginConsultar_ConductorDelegate;
        
        private EndOperationDelegate onEndConsultar_ConductorDelegate;
        
        private System.Threading.SendOrPostCallback onConsultar_ConductorCompletedDelegate;
        
        private BeginOperationDelegate onBeginConsultarPlacaSinParametroDelegate;
        
        private EndOperationDelegate onEndConsultarPlacaSinParametroDelegate;
        
        private System.Threading.SendOrPostCallback onConsultarPlacaSinParametroCompletedDelegate;
        
        private BeginOperationDelegate onBeginConsultarPlacaDelegate;
        
        private EndOperationDelegate onEndConsultarPlacaDelegate;
        
        private System.Threading.SendOrPostCallback onConsultarPlacaCompletedDelegate;
        
        private BeginOperationDelegate onBeginOpenDelegate;
        
        private EndOperationDelegate onEndOpenDelegate;
        
        private System.Threading.SendOrPostCallback onOpenCompletedDelegate;
        
        private BeginOperationDelegate onBeginCloseDelegate;
        
        private EndOperationDelegate onEndCloseDelegate;
        
        private System.Threading.SendOrPostCallback onCloseCompletedDelegate;
        
        public VehiculoServiceClient() {
        }
        
        public VehiculoServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public VehiculoServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public VehiculoServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public VehiculoServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Net.CookieContainer CookieContainer {
            get {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    return httpCookieContainerManager.CookieContainer;
                }
                else {
                    return null;
                }
            }
            set {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    httpCookieContainerManager.CookieContainer = value;
                }
                else {
                    throw new System.InvalidOperationException("Unable to set the CookieContainer. Please make sure the binding contains an HttpC" +
                            "ookieContainerBindingElement.");
                }
            }
        }
        
        public event System.EventHandler<Registrar_VehiculoCompletedEventArgs> Registrar_VehiculoCompleted;
        
        public event System.EventHandler<Consultar_VehiculoCompletedEventArgs> Consultar_VehiculoCompleted;
        
        public event System.EventHandler<Consultar_ExistenciaCompletedEventArgs> Consultar_ExistenciaCompleted;
        
        public event System.EventHandler<Modificar_VehiculoCompletedEventArgs> Modificar_VehiculoCompleted;
        
        public event System.EventHandler<Consultar_ConductorCompletedEventArgs> Consultar_ConductorCompleted;
        
        public event System.EventHandler<ConsultarPlacaSinParametroCompletedEventArgs> ConsultarPlacaSinParametroCompleted;
        
        public event System.EventHandler<ConsultarPlacaCompletedEventArgs> ConsultarPlacaCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> OpenCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> CloseCompleted;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult CYLTRACK_PHONE.VehiculoService.IVehiculoService.BeginRegistrar_Vehiculo(CYLTRACK_PHONE.VehiculoService.VehiculoBE vehiculo, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginRegistrar_Vehiculo(vehiculo, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        string CYLTRACK_PHONE.VehiculoService.IVehiculoService.EndRegistrar_Vehiculo(System.IAsyncResult result) {
            return base.Channel.EndRegistrar_Vehiculo(result);
        }
        
        private System.IAsyncResult OnBeginRegistrar_Vehiculo(object[] inValues, System.AsyncCallback callback, object asyncState) {
            CYLTRACK_PHONE.VehiculoService.VehiculoBE vehiculo = ((CYLTRACK_PHONE.VehiculoService.VehiculoBE)(inValues[0]));
            return ((CYLTRACK_PHONE.VehiculoService.IVehiculoService)(this)).BeginRegistrar_Vehiculo(vehiculo, callback, asyncState);
        }
        
        private object[] OnEndRegistrar_Vehiculo(System.IAsyncResult result) {
            string retVal = ((CYLTRACK_PHONE.VehiculoService.IVehiculoService)(this)).EndRegistrar_Vehiculo(result);
            return new object[] {
                    retVal};
        }
        
        private void OnRegistrar_VehiculoCompleted(object state) {
            if ((this.Registrar_VehiculoCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.Registrar_VehiculoCompleted(this, new Registrar_VehiculoCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void Registrar_VehiculoAsync(CYLTRACK_PHONE.VehiculoService.VehiculoBE vehiculo) {
            this.Registrar_VehiculoAsync(vehiculo, null);
        }
        
        public void Registrar_VehiculoAsync(CYLTRACK_PHONE.VehiculoService.VehiculoBE vehiculo, object userState) {
            if ((this.onBeginRegistrar_VehiculoDelegate == null)) {
                this.onBeginRegistrar_VehiculoDelegate = new BeginOperationDelegate(this.OnBeginRegistrar_Vehiculo);
            }
            if ((this.onEndRegistrar_VehiculoDelegate == null)) {
                this.onEndRegistrar_VehiculoDelegate = new EndOperationDelegate(this.OnEndRegistrar_Vehiculo);
            }
            if ((this.onRegistrar_VehiculoCompletedDelegate == null)) {
                this.onRegistrar_VehiculoCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnRegistrar_VehiculoCompleted);
            }
            base.InvokeAsync(this.onBeginRegistrar_VehiculoDelegate, new object[] {
                        vehiculo}, this.onEndRegistrar_VehiculoDelegate, this.onRegistrar_VehiculoCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult CYLTRACK_PHONE.VehiculoService.IVehiculoService.BeginConsultar_Vehiculo(string vehiculo, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginConsultar_Vehiculo(vehiculo, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CYLTRACK_PHONE.VehiculoService.VehiculoBE CYLTRACK_PHONE.VehiculoService.IVehiculoService.EndConsultar_Vehiculo(System.IAsyncResult result) {
            return base.Channel.EndConsultar_Vehiculo(result);
        }
        
        private System.IAsyncResult OnBeginConsultar_Vehiculo(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string vehiculo = ((string)(inValues[0]));
            return ((CYLTRACK_PHONE.VehiculoService.IVehiculoService)(this)).BeginConsultar_Vehiculo(vehiculo, callback, asyncState);
        }
        
        private object[] OnEndConsultar_Vehiculo(System.IAsyncResult result) {
            CYLTRACK_PHONE.VehiculoService.VehiculoBE retVal = ((CYLTRACK_PHONE.VehiculoService.IVehiculoService)(this)).EndConsultar_Vehiculo(result);
            return new object[] {
                    retVal};
        }
        
        private void OnConsultar_VehiculoCompleted(object state) {
            if ((this.Consultar_VehiculoCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.Consultar_VehiculoCompleted(this, new Consultar_VehiculoCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void Consultar_VehiculoAsync(string vehiculo) {
            this.Consultar_VehiculoAsync(vehiculo, null);
        }
        
        public void Consultar_VehiculoAsync(string vehiculo, object userState) {
            if ((this.onBeginConsultar_VehiculoDelegate == null)) {
                this.onBeginConsultar_VehiculoDelegate = new BeginOperationDelegate(this.OnBeginConsultar_Vehiculo);
            }
            if ((this.onEndConsultar_VehiculoDelegate == null)) {
                this.onEndConsultar_VehiculoDelegate = new EndOperationDelegate(this.OnEndConsultar_Vehiculo);
            }
            if ((this.onConsultar_VehiculoCompletedDelegate == null)) {
                this.onConsultar_VehiculoCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnConsultar_VehiculoCompleted);
            }
            base.InvokeAsync(this.onBeginConsultar_VehiculoDelegate, new object[] {
                        vehiculo}, this.onEndConsultar_VehiculoDelegate, this.onConsultar_VehiculoCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult CYLTRACK_PHONE.VehiculoService.IVehiculoService.BeginConsultar_Existencia(string consultar_existencia, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginConsultar_Existencia(consultar_existencia, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        string CYLTRACK_PHONE.VehiculoService.IVehiculoService.EndConsultar_Existencia(System.IAsyncResult result) {
            return base.Channel.EndConsultar_Existencia(result);
        }
        
        private System.IAsyncResult OnBeginConsultar_Existencia(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string consultar_existencia = ((string)(inValues[0]));
            return ((CYLTRACK_PHONE.VehiculoService.IVehiculoService)(this)).BeginConsultar_Existencia(consultar_existencia, callback, asyncState);
        }
        
        private object[] OnEndConsultar_Existencia(System.IAsyncResult result) {
            string retVal = ((CYLTRACK_PHONE.VehiculoService.IVehiculoService)(this)).EndConsultar_Existencia(result);
            return new object[] {
                    retVal};
        }
        
        private void OnConsultar_ExistenciaCompleted(object state) {
            if ((this.Consultar_ExistenciaCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.Consultar_ExistenciaCompleted(this, new Consultar_ExistenciaCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void Consultar_ExistenciaAsync(string consultar_existencia) {
            this.Consultar_ExistenciaAsync(consultar_existencia, null);
        }
        
        public void Consultar_ExistenciaAsync(string consultar_existencia, object userState) {
            if ((this.onBeginConsultar_ExistenciaDelegate == null)) {
                this.onBeginConsultar_ExistenciaDelegate = new BeginOperationDelegate(this.OnBeginConsultar_Existencia);
            }
            if ((this.onEndConsultar_ExistenciaDelegate == null)) {
                this.onEndConsultar_ExistenciaDelegate = new EndOperationDelegate(this.OnEndConsultar_Existencia);
            }
            if ((this.onConsultar_ExistenciaCompletedDelegate == null)) {
                this.onConsultar_ExistenciaCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnConsultar_ExistenciaCompleted);
            }
            base.InvokeAsync(this.onBeginConsultar_ExistenciaDelegate, new object[] {
                        consultar_existencia}, this.onEndConsultar_ExistenciaDelegate, this.onConsultar_ExistenciaCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult CYLTRACK_PHONE.VehiculoService.IVehiculoService.BeginModificar_Vehiculo(string vehiculo, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginModificar_Vehiculo(vehiculo, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        string CYLTRACK_PHONE.VehiculoService.IVehiculoService.EndModificar_Vehiculo(System.IAsyncResult result) {
            return base.Channel.EndModificar_Vehiculo(result);
        }
        
        private System.IAsyncResult OnBeginModificar_Vehiculo(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string vehiculo = ((string)(inValues[0]));
            return ((CYLTRACK_PHONE.VehiculoService.IVehiculoService)(this)).BeginModificar_Vehiculo(vehiculo, callback, asyncState);
        }
        
        private object[] OnEndModificar_Vehiculo(System.IAsyncResult result) {
            string retVal = ((CYLTRACK_PHONE.VehiculoService.IVehiculoService)(this)).EndModificar_Vehiculo(result);
            return new object[] {
                    retVal};
        }
        
        private void OnModificar_VehiculoCompleted(object state) {
            if ((this.Modificar_VehiculoCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.Modificar_VehiculoCompleted(this, new Modificar_VehiculoCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void Modificar_VehiculoAsync(string vehiculo) {
            this.Modificar_VehiculoAsync(vehiculo, null);
        }
        
        public void Modificar_VehiculoAsync(string vehiculo, object userState) {
            if ((this.onBeginModificar_VehiculoDelegate == null)) {
                this.onBeginModificar_VehiculoDelegate = new BeginOperationDelegate(this.OnBeginModificar_Vehiculo);
            }
            if ((this.onEndModificar_VehiculoDelegate == null)) {
                this.onEndModificar_VehiculoDelegate = new EndOperationDelegate(this.OnEndModificar_Vehiculo);
            }
            if ((this.onModificar_VehiculoCompletedDelegate == null)) {
                this.onModificar_VehiculoCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnModificar_VehiculoCompleted);
            }
            base.InvokeAsync(this.onBeginModificar_VehiculoDelegate, new object[] {
                        vehiculo}, this.onEndModificar_VehiculoDelegate, this.onModificar_VehiculoCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult CYLTRACK_PHONE.VehiculoService.IVehiculoService.BeginConsultar_Conductor(string conductor, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginConsultar_Conductor(conductor, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CYLTRACK_PHONE.VehiculoService.VehiculoBE CYLTRACK_PHONE.VehiculoService.IVehiculoService.EndConsultar_Conductor(System.IAsyncResult result) {
            return base.Channel.EndConsultar_Conductor(result);
        }
        
        private System.IAsyncResult OnBeginConsultar_Conductor(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string conductor = ((string)(inValues[0]));
            return ((CYLTRACK_PHONE.VehiculoService.IVehiculoService)(this)).BeginConsultar_Conductor(conductor, callback, asyncState);
        }
        
        private object[] OnEndConsultar_Conductor(System.IAsyncResult result) {
            CYLTRACK_PHONE.VehiculoService.VehiculoBE retVal = ((CYLTRACK_PHONE.VehiculoService.IVehiculoService)(this)).EndConsultar_Conductor(result);
            return new object[] {
                    retVal};
        }
        
        private void OnConsultar_ConductorCompleted(object state) {
            if ((this.Consultar_ConductorCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.Consultar_ConductorCompleted(this, new Consultar_ConductorCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void Consultar_ConductorAsync(string conductor) {
            this.Consultar_ConductorAsync(conductor, null);
        }
        
        public void Consultar_ConductorAsync(string conductor, object userState) {
            if ((this.onBeginConsultar_ConductorDelegate == null)) {
                this.onBeginConsultar_ConductorDelegate = new BeginOperationDelegate(this.OnBeginConsultar_Conductor);
            }
            if ((this.onEndConsultar_ConductorDelegate == null)) {
                this.onEndConsultar_ConductorDelegate = new EndOperationDelegate(this.OnEndConsultar_Conductor);
            }
            if ((this.onConsultar_ConductorCompletedDelegate == null)) {
                this.onConsultar_ConductorCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnConsultar_ConductorCompleted);
            }
            base.InvokeAsync(this.onBeginConsultar_ConductorDelegate, new object[] {
                        conductor}, this.onEndConsultar_ConductorDelegate, this.onConsultar_ConductorCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult CYLTRACK_PHONE.VehiculoService.IVehiculoService.BeginConsultarPlacaSinParametro(System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginConsultarPlacaSinParametro(callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Collections.ObjectModel.ObservableCollection<string> CYLTRACK_PHONE.VehiculoService.IVehiculoService.EndConsultarPlacaSinParametro(System.IAsyncResult result) {
            return base.Channel.EndConsultarPlacaSinParametro(result);
        }
        
        private System.IAsyncResult OnBeginConsultarPlacaSinParametro(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((CYLTRACK_PHONE.VehiculoService.IVehiculoService)(this)).BeginConsultarPlacaSinParametro(callback, asyncState);
        }
        
        private object[] OnEndConsultarPlacaSinParametro(System.IAsyncResult result) {
            System.Collections.ObjectModel.ObservableCollection<string> retVal = ((CYLTRACK_PHONE.VehiculoService.IVehiculoService)(this)).EndConsultarPlacaSinParametro(result);
            return new object[] {
                    retVal};
        }
        
        private void OnConsultarPlacaSinParametroCompleted(object state) {
            if ((this.ConsultarPlacaSinParametroCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.ConsultarPlacaSinParametroCompleted(this, new ConsultarPlacaSinParametroCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void ConsultarPlacaSinParametroAsync() {
            this.ConsultarPlacaSinParametroAsync(null);
        }
        
        public void ConsultarPlacaSinParametroAsync(object userState) {
            if ((this.onBeginConsultarPlacaSinParametroDelegate == null)) {
                this.onBeginConsultarPlacaSinParametroDelegate = new BeginOperationDelegate(this.OnBeginConsultarPlacaSinParametro);
            }
            if ((this.onEndConsultarPlacaSinParametroDelegate == null)) {
                this.onEndConsultarPlacaSinParametroDelegate = new EndOperationDelegate(this.OnEndConsultarPlacaSinParametro);
            }
            if ((this.onConsultarPlacaSinParametroCompletedDelegate == null)) {
                this.onConsultarPlacaSinParametroCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnConsultarPlacaSinParametroCompleted);
            }
            base.InvokeAsync(this.onBeginConsultarPlacaSinParametroDelegate, null, this.onEndConsultarPlacaSinParametroDelegate, this.onConsultarPlacaSinParametroCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult CYLTRACK_PHONE.VehiculoService.IVehiculoService.BeginConsultarPlaca(string ciudad, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginConsultarPlaca(ciudad, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Collections.ObjectModel.ObservableCollection<string> CYLTRACK_PHONE.VehiculoService.IVehiculoService.EndConsultarPlaca(System.IAsyncResult result) {
            return base.Channel.EndConsultarPlaca(result);
        }
        
        private System.IAsyncResult OnBeginConsultarPlaca(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string ciudad = ((string)(inValues[0]));
            return ((CYLTRACK_PHONE.VehiculoService.IVehiculoService)(this)).BeginConsultarPlaca(ciudad, callback, asyncState);
        }
        
        private object[] OnEndConsultarPlaca(System.IAsyncResult result) {
            System.Collections.ObjectModel.ObservableCollection<string> retVal = ((CYLTRACK_PHONE.VehiculoService.IVehiculoService)(this)).EndConsultarPlaca(result);
            return new object[] {
                    retVal};
        }
        
        private void OnConsultarPlacaCompleted(object state) {
            if ((this.ConsultarPlacaCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.ConsultarPlacaCompleted(this, new ConsultarPlacaCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void ConsultarPlacaAsync(string ciudad) {
            this.ConsultarPlacaAsync(ciudad, null);
        }
        
        public void ConsultarPlacaAsync(string ciudad, object userState) {
            if ((this.onBeginConsultarPlacaDelegate == null)) {
                this.onBeginConsultarPlacaDelegate = new BeginOperationDelegate(this.OnBeginConsultarPlaca);
            }
            if ((this.onEndConsultarPlacaDelegate == null)) {
                this.onEndConsultarPlacaDelegate = new EndOperationDelegate(this.OnEndConsultarPlaca);
            }
            if ((this.onConsultarPlacaCompletedDelegate == null)) {
                this.onConsultarPlacaCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnConsultarPlacaCompleted);
            }
            base.InvokeAsync(this.onBeginConsultarPlacaDelegate, new object[] {
                        ciudad}, this.onEndConsultarPlacaDelegate, this.onConsultarPlacaCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginOpen(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(callback, asyncState);
        }
        
        private object[] OnEndOpen(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndOpen(result);
            return null;
        }
        
        private void OnOpenCompleted(object state) {
            if ((this.OpenCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.OpenCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void OpenAsync() {
            this.OpenAsync(null);
        }
        
        public void OpenAsync(object userState) {
            if ((this.onBeginOpenDelegate == null)) {
                this.onBeginOpenDelegate = new BeginOperationDelegate(this.OnBeginOpen);
            }
            if ((this.onEndOpenDelegate == null)) {
                this.onEndOpenDelegate = new EndOperationDelegate(this.OnEndOpen);
            }
            if ((this.onOpenCompletedDelegate == null)) {
                this.onOpenCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnOpenCompleted);
            }
            base.InvokeAsync(this.onBeginOpenDelegate, null, this.onEndOpenDelegate, this.onOpenCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginClose(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginClose(callback, asyncState);
        }
        
        private object[] OnEndClose(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndClose(result);
            return null;
        }
        
        private void OnCloseCompleted(object state) {
            if ((this.CloseCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.CloseCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void CloseAsync() {
            this.CloseAsync(null);
        }
        
        public void CloseAsync(object userState) {
            if ((this.onBeginCloseDelegate == null)) {
                this.onBeginCloseDelegate = new BeginOperationDelegate(this.OnBeginClose);
            }
            if ((this.onEndCloseDelegate == null)) {
                this.onEndCloseDelegate = new EndOperationDelegate(this.OnEndClose);
            }
            if ((this.onCloseCompletedDelegate == null)) {
                this.onCloseCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCloseCompleted);
            }
            base.InvokeAsync(this.onBeginCloseDelegate, null, this.onEndCloseDelegate, this.onCloseCompletedDelegate, userState);
        }
        
        protected override CYLTRACK_PHONE.VehiculoService.IVehiculoService CreateChannel() {
            return new VehiculoServiceClientChannel(this);
        }
        
        private class VehiculoServiceClientChannel : ChannelBase<CYLTRACK_PHONE.VehiculoService.IVehiculoService>, CYLTRACK_PHONE.VehiculoService.IVehiculoService {
            
            public VehiculoServiceClientChannel(System.ServiceModel.ClientBase<CYLTRACK_PHONE.VehiculoService.IVehiculoService> client) : 
                    base(client) {
            }
            
            public System.IAsyncResult BeginRegistrar_Vehiculo(CYLTRACK_PHONE.VehiculoService.VehiculoBE vehiculo, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = vehiculo;
                System.IAsyncResult _result = base.BeginInvoke("Registrar_Vehiculo", _args, callback, asyncState);
                return _result;
            }
            
            public string EndRegistrar_Vehiculo(System.IAsyncResult result) {
                object[] _args = new object[0];
                string _result = ((string)(base.EndInvoke("Registrar_Vehiculo", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginConsultar_Vehiculo(string vehiculo, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = vehiculo;
                System.IAsyncResult _result = base.BeginInvoke("Consultar_Vehiculo", _args, callback, asyncState);
                return _result;
            }
            
            public CYLTRACK_PHONE.VehiculoService.VehiculoBE EndConsultar_Vehiculo(System.IAsyncResult result) {
                object[] _args = new object[0];
                CYLTRACK_PHONE.VehiculoService.VehiculoBE _result = ((CYLTRACK_PHONE.VehiculoService.VehiculoBE)(base.EndInvoke("Consultar_Vehiculo", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginConsultar_Existencia(string consultar_existencia, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = consultar_existencia;
                System.IAsyncResult _result = base.BeginInvoke("Consultar_Existencia", _args, callback, asyncState);
                return _result;
            }
            
            public string EndConsultar_Existencia(System.IAsyncResult result) {
                object[] _args = new object[0];
                string _result = ((string)(base.EndInvoke("Consultar_Existencia", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginModificar_Vehiculo(string vehiculo, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = vehiculo;
                System.IAsyncResult _result = base.BeginInvoke("Modificar_Vehiculo", _args, callback, asyncState);
                return _result;
            }
            
            public string EndModificar_Vehiculo(System.IAsyncResult result) {
                object[] _args = new object[0];
                string _result = ((string)(base.EndInvoke("Modificar_Vehiculo", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginConsultar_Conductor(string conductor, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = conductor;
                System.IAsyncResult _result = base.BeginInvoke("Consultar_Conductor", _args, callback, asyncState);
                return _result;
            }
            
            public CYLTRACK_PHONE.VehiculoService.VehiculoBE EndConsultar_Conductor(System.IAsyncResult result) {
                object[] _args = new object[0];
                CYLTRACK_PHONE.VehiculoService.VehiculoBE _result = ((CYLTRACK_PHONE.VehiculoService.VehiculoBE)(base.EndInvoke("Consultar_Conductor", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginConsultarPlacaSinParametro(System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[0];
                System.IAsyncResult _result = base.BeginInvoke("ConsultarPlacaSinParametro", _args, callback, asyncState);
                return _result;
            }
            
            public System.Collections.ObjectModel.ObservableCollection<string> EndConsultarPlacaSinParametro(System.IAsyncResult result) {
                object[] _args = new object[0];
                System.Collections.ObjectModel.ObservableCollection<string> _result = ((System.Collections.ObjectModel.ObservableCollection<string>)(base.EndInvoke("ConsultarPlacaSinParametro", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginConsultarPlaca(string ciudad, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = ciudad;
                System.IAsyncResult _result = base.BeginInvoke("ConsultarPlaca", _args, callback, asyncState);
                return _result;
            }
            
            public System.Collections.ObjectModel.ObservableCollection<string> EndConsultarPlaca(System.IAsyncResult result) {
                object[] _args = new object[0];
                System.Collections.ObjectModel.ObservableCollection<string> _result = ((System.Collections.ObjectModel.ObservableCollection<string>)(base.EndInvoke("ConsultarPlaca", _args, result)));
                return _result;
            }
        }
    }
}
