//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.18444
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This code was auto-generated by Microsoft.Silverlight.Phone.ServiceReference, version 3.7.0.0
// 
namespace CYLTRACK_PHONE.VehiculoService {
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="VehiculoBE", Namespace="http://schemas.datacontract.org/2004/07/Unisangil.CYLTRACK.CYLTRACK_BE")]
    public partial class VehiculoBE : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string ChasisField;
        
        private string CilindrajeField;
        
        private CYLTRACK_PHONE.VehiculoService.ConductorBE ConductorField;
        
        private CYLTRACK_PHONE.VehiculoService.ContratistaBE ContratistaField;
        
        private string EstadoField;
        
        private string Id_UbicacionField;
        
        private string Id_VehiculoField;
        
        private string MarcaField;
        
        private string ModeloField;
        
        private string MotorField;
        
        private string PlacaField;
        
        private CYLTRACK_PHONE.VehiculoService.RutaBE RutaField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Chasis {
            get {
                return this.ChasisField;
            }
            set {
                if ((object.ReferenceEquals(this.ChasisField, value) != true)) {
                    this.ChasisField = value;
                    this.RaisePropertyChanged("Chasis");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Cilindraje {
            get {
                return this.CilindrajeField;
            }
            set {
                if ((object.ReferenceEquals(this.CilindrajeField, value) != true)) {
                    this.CilindrajeField = value;
                    this.RaisePropertyChanged("Cilindraje");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CYLTRACK_PHONE.VehiculoService.ConductorBE Conductor {
            get {
                return this.ConductorField;
            }
            set {
                if ((object.ReferenceEquals(this.ConductorField, value) != true)) {
                    this.ConductorField = value;
                    this.RaisePropertyChanged("Conductor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CYLTRACK_PHONE.VehiculoService.ContratistaBE Contratista {
            get {
                return this.ContratistaField;
            }
            set {
                if ((object.ReferenceEquals(this.ContratistaField, value) != true)) {
                    this.ContratistaField = value;
                    this.RaisePropertyChanged("Contratista");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Estado {
            get {
                return this.EstadoField;
            }
            set {
                if ((object.ReferenceEquals(this.EstadoField, value) != true)) {
                    this.EstadoField = value;
                    this.RaisePropertyChanged("Estado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Id_Ubicacion {
            get {
                return this.Id_UbicacionField;
            }
            set {
                if ((object.ReferenceEquals(this.Id_UbicacionField, value) != true)) {
                    this.Id_UbicacionField = value;
                    this.RaisePropertyChanged("Id_Ubicacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Id_Vehiculo {
            get {
                return this.Id_VehiculoField;
            }
            set {
                if ((object.ReferenceEquals(this.Id_VehiculoField, value) != true)) {
                    this.Id_VehiculoField = value;
                    this.RaisePropertyChanged("Id_Vehiculo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Marca {
            get {
                return this.MarcaField;
            }
            set {
                if ((object.ReferenceEquals(this.MarcaField, value) != true)) {
                    this.MarcaField = value;
                    this.RaisePropertyChanged("Marca");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Modelo {
            get {
                return this.ModeloField;
            }
            set {
                if ((object.ReferenceEquals(this.ModeloField, value) != true)) {
                    this.ModeloField = value;
                    this.RaisePropertyChanged("Modelo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Motor {
            get {
                return this.MotorField;
            }
            set {
                if ((object.ReferenceEquals(this.MotorField, value) != true)) {
                    this.MotorField = value;
                    this.RaisePropertyChanged("Motor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Placa {
            get {
                return this.PlacaField;
            }
            set {
                if ((object.ReferenceEquals(this.PlacaField, value) != true)) {
                    this.PlacaField = value;
                    this.RaisePropertyChanged("Placa");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CYLTRACK_PHONE.VehiculoService.RutaBE Ruta {
            get {
                return this.RutaField;
            }
            set {
                if ((object.ReferenceEquals(this.RutaField, value) != true)) {
                    this.RutaField = value;
                    this.RaisePropertyChanged("Ruta");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ConductorBE", Namespace="http://schemas.datacontract.org/2004/07/Unisangil.CYLTRACK.CYLTRACK_BE")]
    public partial class ConductorBE : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string Apellido_1Field;
        
        private string Apellido_2Field;
        
        private string BarrioField;
        
        private string CedulaField;
        
        private CYLTRACK_PHONE.VehiculoService.CiudadBE CiudadField;
        
        private string DireccionField;
        
        private string Id_ConductorField;
        
        private string Nombres_ConductorField;
        
        private string TelefonoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Apellido_1 {
            get {
                return this.Apellido_1Field;
            }
            set {
                if ((object.ReferenceEquals(this.Apellido_1Field, value) != true)) {
                    this.Apellido_1Field = value;
                    this.RaisePropertyChanged("Apellido_1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Apellido_2 {
            get {
                return this.Apellido_2Field;
            }
            set {
                if ((object.ReferenceEquals(this.Apellido_2Field, value) != true)) {
                    this.Apellido_2Field = value;
                    this.RaisePropertyChanged("Apellido_2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Barrio {
            get {
                return this.BarrioField;
            }
            set {
                if ((object.ReferenceEquals(this.BarrioField, value) != true)) {
                    this.BarrioField = value;
                    this.RaisePropertyChanged("Barrio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Cedula {
            get {
                return this.CedulaField;
            }
            set {
                if ((object.ReferenceEquals(this.CedulaField, value) != true)) {
                    this.CedulaField = value;
                    this.RaisePropertyChanged("Cedula");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CYLTRACK_PHONE.VehiculoService.CiudadBE Ciudad {
            get {
                return this.CiudadField;
            }
            set {
                if ((object.ReferenceEquals(this.CiudadField, value) != true)) {
                    this.CiudadField = value;
                    this.RaisePropertyChanged("Ciudad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Direccion {
            get {
                return this.DireccionField;
            }
            set {
                if ((object.ReferenceEquals(this.DireccionField, value) != true)) {
                    this.DireccionField = value;
                    this.RaisePropertyChanged("Direccion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Id_Conductor {
            get {
                return this.Id_ConductorField;
            }
            set {
                if ((object.ReferenceEquals(this.Id_ConductorField, value) != true)) {
                    this.Id_ConductorField = value;
                    this.RaisePropertyChanged("Id_Conductor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombres_Conductor {
            get {
                return this.Nombres_ConductorField;
            }
            set {
                if ((object.ReferenceEquals(this.Nombres_ConductorField, value) != true)) {
                    this.Nombres_ConductorField = value;
                    this.RaisePropertyChanged("Nombres_Conductor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Telefono {
            get {
                return this.TelefonoField;
            }
            set {
                if ((object.ReferenceEquals(this.TelefonoField, value) != true)) {
                    this.TelefonoField = value;
                    this.RaisePropertyChanged("Telefono");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ContratistaBE", Namespace="http://schemas.datacontract.org/2004/07/Unisangil.CYLTRACK.CYLTRACK_BE")]
    public partial class ContratistaBE : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string ApellidosField;
        
        private string CedulaField;
        
        private string DireccionField;
        
        private string Id_ContratistaField;
        
        private string NombresField;
        
        private string TelefonoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Apellidos {
            get {
                return this.ApellidosField;
            }
            set {
                if ((object.ReferenceEquals(this.ApellidosField, value) != true)) {
                    this.ApellidosField = value;
                    this.RaisePropertyChanged("Apellidos");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Cedula {
            get {
                return this.CedulaField;
            }
            set {
                if ((object.ReferenceEquals(this.CedulaField, value) != true)) {
                    this.CedulaField = value;
                    this.RaisePropertyChanged("Cedula");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Direccion {
            get {
                return this.DireccionField;
            }
            set {
                if ((object.ReferenceEquals(this.DireccionField, value) != true)) {
                    this.DireccionField = value;
                    this.RaisePropertyChanged("Direccion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Id_Contratista {
            get {
                return this.Id_ContratistaField;
            }
            set {
                if ((object.ReferenceEquals(this.Id_ContratistaField, value) != true)) {
                    this.Id_ContratistaField = value;
                    this.RaisePropertyChanged("Id_Contratista");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombres {
            get {
                return this.NombresField;
            }
            set {
                if ((object.ReferenceEquals(this.NombresField, value) != true)) {
                    this.NombresField = value;
                    this.RaisePropertyChanged("Nombres");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Telefono {
            get {
                return this.TelefonoField;
            }
            set {
                if ((object.ReferenceEquals(this.TelefonoField, value) != true)) {
                    this.TelefonoField = value;
                    this.RaisePropertyChanged("Telefono");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RutaBE", Namespace="http://schemas.datacontract.org/2004/07/Unisangil.CYLTRACK.CYLTRACK_BE")]
    public partial class RutaBE : object, System.ComponentModel.INotifyPropertyChanged {
        
        private CYLTRACK_PHONE.VehiculoService.Ciudad_RutaBE Ciudad_RutaField;
        
        private string Id_RutaField;
        
        private string Nombre_RutaField;
        
        private CYLTRACK_PHONE.VehiculoService.Ruta_VehiculoBE Ruta_VehiculoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CYLTRACK_PHONE.VehiculoService.Ciudad_RutaBE Ciudad_Ruta {
            get {
                return this.Ciudad_RutaField;
            }
            set {
                if ((object.ReferenceEquals(this.Ciudad_RutaField, value) != true)) {
                    this.Ciudad_RutaField = value;
                    this.RaisePropertyChanged("Ciudad_Ruta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Id_Ruta {
            get {
                return this.Id_RutaField;
            }
            set {
                if ((object.ReferenceEquals(this.Id_RutaField, value) != true)) {
                    this.Id_RutaField = value;
                    this.RaisePropertyChanged("Id_Ruta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre_Ruta {
            get {
                return this.Nombre_RutaField;
            }
            set {
                if ((object.ReferenceEquals(this.Nombre_RutaField, value) != true)) {
                    this.Nombre_RutaField = value;
                    this.RaisePropertyChanged("Nombre_Ruta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CYLTRACK_PHONE.VehiculoService.Ruta_VehiculoBE Ruta_Vehiculo {
            get {
                return this.Ruta_VehiculoField;
            }
            set {
                if ((object.ReferenceEquals(this.Ruta_VehiculoField, value) != true)) {
                    this.Ruta_VehiculoField = value;
                    this.RaisePropertyChanged("Ruta_Vehiculo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CiudadBE", Namespace="http://schemas.datacontract.org/2004/07/Unisangil.CYLTRACK.CYLTRACK_BE")]
    public partial class CiudadBE : object, System.ComponentModel.INotifyPropertyChanged {
        
        private CYLTRACK_PHONE.VehiculoService.DepartamentoBE DepartamentoField;
        
        private string Id_CiudadField;
        
        private string Nombre_CiudadField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CYLTRACK_PHONE.VehiculoService.DepartamentoBE Departamento {
            get {
                return this.DepartamentoField;
            }
            set {
                if ((object.ReferenceEquals(this.DepartamentoField, value) != true)) {
                    this.DepartamentoField = value;
                    this.RaisePropertyChanged("Departamento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Id_Ciudad {
            get {
                return this.Id_CiudadField;
            }
            set {
                if ((object.ReferenceEquals(this.Id_CiudadField, value) != true)) {
                    this.Id_CiudadField = value;
                    this.RaisePropertyChanged("Id_Ciudad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre_Ciudad {
            get {
                return this.Nombre_CiudadField;
            }
            set {
                if ((object.ReferenceEquals(this.Nombre_CiudadField, value) != true)) {
                    this.Nombre_CiudadField = value;
                    this.RaisePropertyChanged("Nombre_Ciudad");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DepartamentoBE", Namespace="http://schemas.datacontract.org/2004/07/Unisangil.CYLTRACK.CYLTRACK_BE")]
    public partial class DepartamentoBE : object, System.ComponentModel.INotifyPropertyChanged {
        
        private CYLTRACK_PHONE.VehiculoService.CiudadBE CiudadField;
        
        private string Id_DepartamentoField;
        
        private string Nombre_DepartamentoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CYLTRACK_PHONE.VehiculoService.CiudadBE Ciudad {
            get {
                return this.CiudadField;
            }
            set {
                if ((object.ReferenceEquals(this.CiudadField, value) != true)) {
                    this.CiudadField = value;
                    this.RaisePropertyChanged("Ciudad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Id_Departamento {
            get {
                return this.Id_DepartamentoField;
            }
            set {
                if ((object.ReferenceEquals(this.Id_DepartamentoField, value) != true)) {
                    this.Id_DepartamentoField = value;
                    this.RaisePropertyChanged("Id_Departamento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre_Departamento {
            get {
                return this.Nombre_DepartamentoField;
            }
            set {
                if ((object.ReferenceEquals(this.Nombre_DepartamentoField, value) != true)) {
                    this.Nombre_DepartamentoField = value;
                    this.RaisePropertyChanged("Nombre_Departamento");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Ciudad_RutaBE", Namespace="http://schemas.datacontract.org/2004/07/Unisangil.CYLTRACK.CYLTRACK_BE")]
    public partial class Ciudad_RutaBE : object, System.ComponentModel.INotifyPropertyChanged {
        
        private CYLTRACK_PHONE.VehiculoService.CiudadBE CiudadField;
        
        private string Id_Ciudad_RutaField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CYLTRACK_PHONE.VehiculoService.CiudadBE Ciudad {
            get {
                return this.CiudadField;
            }
            set {
                if ((object.ReferenceEquals(this.CiudadField, value) != true)) {
                    this.CiudadField = value;
                    this.RaisePropertyChanged("Ciudad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Id_Ciudad_Ruta {
            get {
                return this.Id_Ciudad_RutaField;
            }
            set {
                if ((object.ReferenceEquals(this.Id_Ciudad_RutaField, value) != true)) {
                    this.Id_Ciudad_RutaField = value;
                    this.RaisePropertyChanged("Id_Ciudad_Ruta");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Ruta_VehiculoBE", Namespace="http://schemas.datacontract.org/2004/07/Unisangil.CYLTRACK.CYLTRACK_BE")]
    public partial class Ruta_VehiculoBE : object, System.ComponentModel.INotifyPropertyChanged {
        
        private CYLTRACK_PHONE.VehiculoService.CiudadBE CiudadField;
        
        private string EstadoField;
        
        private string Fecha_FinField;
        
        private string Fecha_InicioField;
        
        private string Id_Ruta_VehiculoField;
        
        private System.Collections.ObjectModel.ObservableCollection<CYLTRACK_PHONE.VehiculoService.VehiculoBE> ListaVehiculoField;
        
        private CYLTRACK_PHONE.VehiculoService.VehiculoBE VehiculoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CYLTRACK_PHONE.VehiculoService.CiudadBE Ciudad {
            get {
                return this.CiudadField;
            }
            set {
                if ((object.ReferenceEquals(this.CiudadField, value) != true)) {
                    this.CiudadField = value;
                    this.RaisePropertyChanged("Ciudad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Estado {
            get {
                return this.EstadoField;
            }
            set {
                if ((object.ReferenceEquals(this.EstadoField, value) != true)) {
                    this.EstadoField = value;
                    this.RaisePropertyChanged("Estado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Fecha_Fin {
            get {
                return this.Fecha_FinField;
            }
            set {
                if ((object.ReferenceEquals(this.Fecha_FinField, value) != true)) {
                    this.Fecha_FinField = value;
                    this.RaisePropertyChanged("Fecha_Fin");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Fecha_Inicio {
            get {
                return this.Fecha_InicioField;
            }
            set {
                if ((object.ReferenceEquals(this.Fecha_InicioField, value) != true)) {
                    this.Fecha_InicioField = value;
                    this.RaisePropertyChanged("Fecha_Inicio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Id_Ruta_Vehiculo {
            get {
                return this.Id_Ruta_VehiculoField;
            }
            set {
                if ((object.ReferenceEquals(this.Id_Ruta_VehiculoField, value) != true)) {
                    this.Id_Ruta_VehiculoField = value;
                    this.RaisePropertyChanged("Id_Ruta_Vehiculo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.ObjectModel.ObservableCollection<CYLTRACK_PHONE.VehiculoService.VehiculoBE> ListaVehiculo {
            get {
                return this.ListaVehiculoField;
            }
            set {
                if ((object.ReferenceEquals(this.ListaVehiculoField, value) != true)) {
                    this.ListaVehiculoField = value;
                    this.RaisePropertyChanged("ListaVehiculo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CYLTRACK_PHONE.VehiculoService.VehiculoBE Vehiculo {
            get {
                return this.VehiculoField;
            }
            set {
                if ((object.ReferenceEquals(this.VehiculoField, value) != true)) {
                    this.VehiculoField = value;
                    this.RaisePropertyChanged("Vehiculo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://servicios.cyltrack.com.co/cyltrack/", ConfigurationName="VehiculoService.IVehiculoService")]
    public interface IVehiculoService {
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://servicios.cyltrack.com.co/cyltrack/IVehiculoService/Registrar_Vehiculo", ReplyAction="http://servicios.cyltrack.com.co/cyltrack/IVehiculoService/Registrar_VehiculoResp" +
            "onse")]
        System.IAsyncResult BeginRegistrar_Vehiculo(CYLTRACK_PHONE.VehiculoService.VehiculoBE vehiculo, System.AsyncCallback callback, object asyncState);
        
        long EndRegistrar_Vehiculo(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://servicios.cyltrack.com.co/cyltrack/IVehiculoService/ConsultarVehiculo", ReplyAction="http://servicios.cyltrack.com.co/cyltrack/IVehiculoService/ConsultarVehiculoRespo" +
            "nse")]
        System.IAsyncResult BeginConsultarVehiculo(string placa, System.AsyncCallback callback, object asyncState);
        
        System.Collections.ObjectModel.ObservableCollection<CYLTRACK_PHONE.VehiculoService.VehiculoBE> EndConsultarVehiculo(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://servicios.cyltrack.com.co/cyltrack/IVehiculoService/ConsultarExistenciaVeh" +
            "iculo", ReplyAction="http://servicios.cyltrack.com.co/cyltrack/IVehiculoService/ConsultarExistenciaVeh" +
            "iculoResponse")]
        System.IAsyncResult BeginConsultarExistenciaVehiculo(string placa, System.AsyncCallback callback, object asyncState);
        
        long EndConsultarExistenciaVehiculo(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://servicios.cyltrack.com.co/cyltrack/IVehiculoService/ConsultarExistenciaCon" +
            "tratista", ReplyAction="http://servicios.cyltrack.com.co/cyltrack/IVehiculoService/ConsultarExistenciaCon" +
            "tratistaResponse")]
        System.IAsyncResult BeginConsultarExistenciaContratista(string cedula, System.AsyncCallback callback, object asyncState);
        
        long EndConsultarExistenciaContratista(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://servicios.cyltrack.com.co/cyltrack/IVehiculoService/Modificar_Vehiculo", ReplyAction="http://servicios.cyltrack.com.co/cyltrack/IVehiculoService/Modificar_VehiculoResp" +
            "onse")]
        System.IAsyncResult BeginModificar_Vehiculo(CYLTRACK_PHONE.VehiculoService.VehiculoBE vehiculo, System.AsyncCallback callback, object asyncState);
        
        long EndModificar_Vehiculo(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://servicios.cyltrack.com.co/cyltrack/IVehiculoService/Consultar_Conductor", ReplyAction="http://servicios.cyltrack.com.co/cyltrack/IVehiculoService/Consultar_ConductorRes" +
            "ponse")]
        System.IAsyncResult BeginConsultar_Conductor(string cedula, System.AsyncCallback callback, object asyncState);
        
        CYLTRACK_PHONE.VehiculoService.ConductorBE EndConsultar_Conductor(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://servicios.cyltrack.com.co/cyltrack/IVehiculoService/ConsultarPropVehiculo", ReplyAction="http://servicios.cyltrack.com.co/cyltrack/IVehiculoService/ConsultarPropVehiculoR" +
            "esponse")]
        System.IAsyncResult BeginConsultarPropVehiculo(string cedula, System.AsyncCallback callback, object asyncState);
        
        CYLTRACK_PHONE.VehiculoService.ContratistaBE EndConsultarPropVehiculo(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://servicios.cyltrack.com.co/cyltrack/IVehiculoService/RegistrarConductor", ReplyAction="http://servicios.cyltrack.com.co/cyltrack/IVehiculoService/RegistrarConductorResp" +
            "onse")]
        System.IAsyncResult BeginRegistrarConductor(CYLTRACK_PHONE.VehiculoService.ConductorBE conductor, System.AsyncCallback callback, object asyncState);
        
        long EndRegistrarConductor(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://servicios.cyltrack.com.co/cyltrack/IVehiculoService/RegistrarContratista", ReplyAction="http://servicios.cyltrack.com.co/cyltrack/IVehiculoService/RegistrarContratistaRe" +
            "sponse")]
        System.IAsyncResult BeginRegistrarContratista(CYLTRACK_PHONE.VehiculoService.ContratistaBE contratista, System.AsyncCallback callback, object asyncState);
        
        long EndRegistrarContratista(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://servicios.cyltrack.com.co/cyltrack/IVehiculoService/ConsultarExistenciaCon" +
            "ductor", ReplyAction="http://servicios.cyltrack.com.co/cyltrack/IVehiculoService/ConsultarExistenciaCon" +
            "ductorResponse")]
        System.IAsyncResult BeginConsultarExistenciaConductor(string cedula, System.AsyncCallback callback, object asyncState);
        
        long EndConsultarExistenciaConductor(System.IAsyncResult result);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IVehiculoServiceChannel : CYLTRACK_PHONE.VehiculoService.IVehiculoService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Registrar_VehiculoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public Registrar_VehiculoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public long Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((long)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ConsultarVehiculoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public ConsultarVehiculoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public System.Collections.ObjectModel.ObservableCollection<CYLTRACK_PHONE.VehiculoService.VehiculoBE> Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((System.Collections.ObjectModel.ObservableCollection<CYLTRACK_PHONE.VehiculoService.VehiculoBE>)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ConsultarExistenciaVehiculoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public ConsultarExistenciaVehiculoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public long Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((long)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ConsultarExistenciaContratistaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public ConsultarExistenciaContratistaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public long Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((long)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Modificar_VehiculoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public Modificar_VehiculoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public long Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((long)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Consultar_ConductorCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public Consultar_ConductorCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public CYLTRACK_PHONE.VehiculoService.ConductorBE Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((CYLTRACK_PHONE.VehiculoService.ConductorBE)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ConsultarPropVehiculoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public ConsultarPropVehiculoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public CYLTRACK_PHONE.VehiculoService.ContratistaBE Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((CYLTRACK_PHONE.VehiculoService.ContratistaBE)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RegistrarConductorCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public RegistrarConductorCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public long Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((long)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RegistrarContratistaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public RegistrarContratistaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public long Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((long)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ConsultarExistenciaConductorCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public ConsultarExistenciaConductorCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public long Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((long)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class VehiculoServiceClient : System.ServiceModel.ClientBase<CYLTRACK_PHONE.VehiculoService.IVehiculoService>, CYLTRACK_PHONE.VehiculoService.IVehiculoService {
        
        private BeginOperationDelegate onBeginRegistrar_VehiculoDelegate;
        
        private EndOperationDelegate onEndRegistrar_VehiculoDelegate;
        
        private System.Threading.SendOrPostCallback onRegistrar_VehiculoCompletedDelegate;
        
        private BeginOperationDelegate onBeginConsultarVehiculoDelegate;
        
        private EndOperationDelegate onEndConsultarVehiculoDelegate;
        
        private System.Threading.SendOrPostCallback onConsultarVehiculoCompletedDelegate;
        
        private BeginOperationDelegate onBeginConsultarExistenciaVehiculoDelegate;
        
        private EndOperationDelegate onEndConsultarExistenciaVehiculoDelegate;
        
        private System.Threading.SendOrPostCallback onConsultarExistenciaVehiculoCompletedDelegate;
        
        private BeginOperationDelegate onBeginConsultarExistenciaContratistaDelegate;
        
        private EndOperationDelegate onEndConsultarExistenciaContratistaDelegate;
        
        private System.Threading.SendOrPostCallback onConsultarExistenciaContratistaCompletedDelegate;
        
        private BeginOperationDelegate onBeginModificar_VehiculoDelegate;
        
        private EndOperationDelegate onEndModificar_VehiculoDelegate;
        
        private System.Threading.SendOrPostCallback onModificar_VehiculoCompletedDelegate;
        
        private BeginOperationDelegate onBeginConsultar_ConductorDelegate;
        
        private EndOperationDelegate onEndConsultar_ConductorDelegate;
        
        private System.Threading.SendOrPostCallback onConsultar_ConductorCompletedDelegate;
        
        private BeginOperationDelegate onBeginConsultarPropVehiculoDelegate;
        
        private EndOperationDelegate onEndConsultarPropVehiculoDelegate;
        
        private System.Threading.SendOrPostCallback onConsultarPropVehiculoCompletedDelegate;
        
        private BeginOperationDelegate onBeginRegistrarConductorDelegate;
        
        private EndOperationDelegate onEndRegistrarConductorDelegate;
        
        private System.Threading.SendOrPostCallback onRegistrarConductorCompletedDelegate;
        
        private BeginOperationDelegate onBeginRegistrarContratistaDelegate;
        
        private EndOperationDelegate onEndRegistrarContratistaDelegate;
        
        private System.Threading.SendOrPostCallback onRegistrarContratistaCompletedDelegate;
        
        private BeginOperationDelegate onBeginConsultarExistenciaConductorDelegate;
        
        private EndOperationDelegate onEndConsultarExistenciaConductorDelegate;
        
        private System.Threading.SendOrPostCallback onConsultarExistenciaConductorCompletedDelegate;
        
        private BeginOperationDelegate onBeginOpenDelegate;
        
        private EndOperationDelegate onEndOpenDelegate;
        
        private System.Threading.SendOrPostCallback onOpenCompletedDelegate;
        
        private BeginOperationDelegate onBeginCloseDelegate;
        
        private EndOperationDelegate onEndCloseDelegate;
        
        private System.Threading.SendOrPostCallback onCloseCompletedDelegate;
        
        public VehiculoServiceClient() {
        }
        
        public VehiculoServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public VehiculoServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public VehiculoServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public VehiculoServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Net.CookieContainer CookieContainer {
            get {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    return httpCookieContainerManager.CookieContainer;
                }
                else {
                    return null;
                }
            }
            set {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    httpCookieContainerManager.CookieContainer = value;
                }
                else {
                    throw new System.InvalidOperationException("Unable to set the CookieContainer. Please make sure the binding contains an HttpC" +
                            "ookieContainerBindingElement.");
                }
            }
        }
        
        public event System.EventHandler<Registrar_VehiculoCompletedEventArgs> Registrar_VehiculoCompleted;
        
        public event System.EventHandler<ConsultarVehiculoCompletedEventArgs> ConsultarVehiculoCompleted;
        
        public event System.EventHandler<ConsultarExistenciaVehiculoCompletedEventArgs> ConsultarExistenciaVehiculoCompleted;
        
        public event System.EventHandler<ConsultarExistenciaContratistaCompletedEventArgs> ConsultarExistenciaContratistaCompleted;
        
        public event System.EventHandler<Modificar_VehiculoCompletedEventArgs> Modificar_VehiculoCompleted;
        
        public event System.EventHandler<Consultar_ConductorCompletedEventArgs> Consultar_ConductorCompleted;
        
        public event System.EventHandler<ConsultarPropVehiculoCompletedEventArgs> ConsultarPropVehiculoCompleted;
        
        public event System.EventHandler<RegistrarConductorCompletedEventArgs> RegistrarConductorCompleted;
        
        public event System.EventHandler<RegistrarContratistaCompletedEventArgs> RegistrarContratistaCompleted;
        
        public event System.EventHandler<ConsultarExistenciaConductorCompletedEventArgs> ConsultarExistenciaConductorCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> OpenCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> CloseCompleted;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult CYLTRACK_PHONE.VehiculoService.IVehiculoService.BeginRegistrar_Vehiculo(CYLTRACK_PHONE.VehiculoService.VehiculoBE vehiculo, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginRegistrar_Vehiculo(vehiculo, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        long CYLTRACK_PHONE.VehiculoService.IVehiculoService.EndRegistrar_Vehiculo(System.IAsyncResult result) {
            return base.Channel.EndRegistrar_Vehiculo(result);
        }
        
        private System.IAsyncResult OnBeginRegistrar_Vehiculo(object[] inValues, System.AsyncCallback callback, object asyncState) {
            CYLTRACK_PHONE.VehiculoService.VehiculoBE vehiculo = ((CYLTRACK_PHONE.VehiculoService.VehiculoBE)(inValues[0]));
            return ((CYLTRACK_PHONE.VehiculoService.IVehiculoService)(this)).BeginRegistrar_Vehiculo(vehiculo, callback, asyncState);
        }
        
        private object[] OnEndRegistrar_Vehiculo(System.IAsyncResult result) {
            long retVal = ((CYLTRACK_PHONE.VehiculoService.IVehiculoService)(this)).EndRegistrar_Vehiculo(result);
            return new object[] {
                    retVal};
        }
        
        private void OnRegistrar_VehiculoCompleted(object state) {
            if ((this.Registrar_VehiculoCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.Registrar_VehiculoCompleted(this, new Registrar_VehiculoCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void Registrar_VehiculoAsync(CYLTRACK_PHONE.VehiculoService.VehiculoBE vehiculo) {
            this.Registrar_VehiculoAsync(vehiculo, null);
        }
        
        public void Registrar_VehiculoAsync(CYLTRACK_PHONE.VehiculoService.VehiculoBE vehiculo, object userState) {
            if ((this.onBeginRegistrar_VehiculoDelegate == null)) {
                this.onBeginRegistrar_VehiculoDelegate = new BeginOperationDelegate(this.OnBeginRegistrar_Vehiculo);
            }
            if ((this.onEndRegistrar_VehiculoDelegate == null)) {
                this.onEndRegistrar_VehiculoDelegate = new EndOperationDelegate(this.OnEndRegistrar_Vehiculo);
            }
            if ((this.onRegistrar_VehiculoCompletedDelegate == null)) {
                this.onRegistrar_VehiculoCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnRegistrar_VehiculoCompleted);
            }
            base.InvokeAsync(this.onBeginRegistrar_VehiculoDelegate, new object[] {
                        vehiculo}, this.onEndRegistrar_VehiculoDelegate, this.onRegistrar_VehiculoCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult CYLTRACK_PHONE.VehiculoService.IVehiculoService.BeginConsultarVehiculo(string placa, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginConsultarVehiculo(placa, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Collections.ObjectModel.ObservableCollection<CYLTRACK_PHONE.VehiculoService.VehiculoBE> CYLTRACK_PHONE.VehiculoService.IVehiculoService.EndConsultarVehiculo(System.IAsyncResult result) {
            return base.Channel.EndConsultarVehiculo(result);
        }
        
        private System.IAsyncResult OnBeginConsultarVehiculo(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string placa = ((string)(inValues[0]));
            return ((CYLTRACK_PHONE.VehiculoService.IVehiculoService)(this)).BeginConsultarVehiculo(placa, callback, asyncState);
        }
        
        private object[] OnEndConsultarVehiculo(System.IAsyncResult result) {
            System.Collections.ObjectModel.ObservableCollection<CYLTRACK_PHONE.VehiculoService.VehiculoBE> retVal = ((CYLTRACK_PHONE.VehiculoService.IVehiculoService)(this)).EndConsultarVehiculo(result);
            return new object[] {
                    retVal};
        }
        
        private void OnConsultarVehiculoCompleted(object state) {
            if ((this.ConsultarVehiculoCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.ConsultarVehiculoCompleted(this, new ConsultarVehiculoCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void ConsultarVehiculoAsync(string placa) {
            this.ConsultarVehiculoAsync(placa, null);
        }
        
        public void ConsultarVehiculoAsync(string placa, object userState) {
            if ((this.onBeginConsultarVehiculoDelegate == null)) {
                this.onBeginConsultarVehiculoDelegate = new BeginOperationDelegate(this.OnBeginConsultarVehiculo);
            }
            if ((this.onEndConsultarVehiculoDelegate == null)) {
                this.onEndConsultarVehiculoDelegate = new EndOperationDelegate(this.OnEndConsultarVehiculo);
            }
            if ((this.onConsultarVehiculoCompletedDelegate == null)) {
                this.onConsultarVehiculoCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnConsultarVehiculoCompleted);
            }
            base.InvokeAsync(this.onBeginConsultarVehiculoDelegate, new object[] {
                        placa}, this.onEndConsultarVehiculoDelegate, this.onConsultarVehiculoCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult CYLTRACK_PHONE.VehiculoService.IVehiculoService.BeginConsultarExistenciaVehiculo(string placa, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginConsultarExistenciaVehiculo(placa, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        long CYLTRACK_PHONE.VehiculoService.IVehiculoService.EndConsultarExistenciaVehiculo(System.IAsyncResult result) {
            return base.Channel.EndConsultarExistenciaVehiculo(result);
        }
        
        private System.IAsyncResult OnBeginConsultarExistenciaVehiculo(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string placa = ((string)(inValues[0]));
            return ((CYLTRACK_PHONE.VehiculoService.IVehiculoService)(this)).BeginConsultarExistenciaVehiculo(placa, callback, asyncState);
        }
        
        private object[] OnEndConsultarExistenciaVehiculo(System.IAsyncResult result) {
            long retVal = ((CYLTRACK_PHONE.VehiculoService.IVehiculoService)(this)).EndConsultarExistenciaVehiculo(result);
            return new object[] {
                    retVal};
        }
        
        private void OnConsultarExistenciaVehiculoCompleted(object state) {
            if ((this.ConsultarExistenciaVehiculoCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.ConsultarExistenciaVehiculoCompleted(this, new ConsultarExistenciaVehiculoCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void ConsultarExistenciaVehiculoAsync(string placa) {
            this.ConsultarExistenciaVehiculoAsync(placa, null);
        }
        
        public void ConsultarExistenciaVehiculoAsync(string placa, object userState) {
            if ((this.onBeginConsultarExistenciaVehiculoDelegate == null)) {
                this.onBeginConsultarExistenciaVehiculoDelegate = new BeginOperationDelegate(this.OnBeginConsultarExistenciaVehiculo);
            }
            if ((this.onEndConsultarExistenciaVehiculoDelegate == null)) {
                this.onEndConsultarExistenciaVehiculoDelegate = new EndOperationDelegate(this.OnEndConsultarExistenciaVehiculo);
            }
            if ((this.onConsultarExistenciaVehiculoCompletedDelegate == null)) {
                this.onConsultarExistenciaVehiculoCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnConsultarExistenciaVehiculoCompleted);
            }
            base.InvokeAsync(this.onBeginConsultarExistenciaVehiculoDelegate, new object[] {
                        placa}, this.onEndConsultarExistenciaVehiculoDelegate, this.onConsultarExistenciaVehiculoCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult CYLTRACK_PHONE.VehiculoService.IVehiculoService.BeginConsultarExistenciaContratista(string cedula, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginConsultarExistenciaContratista(cedula, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        long CYLTRACK_PHONE.VehiculoService.IVehiculoService.EndConsultarExistenciaContratista(System.IAsyncResult result) {
            return base.Channel.EndConsultarExistenciaContratista(result);
        }
        
        private System.IAsyncResult OnBeginConsultarExistenciaContratista(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string cedula = ((string)(inValues[0]));
            return ((CYLTRACK_PHONE.VehiculoService.IVehiculoService)(this)).BeginConsultarExistenciaContratista(cedula, callback, asyncState);
        }
        
        private object[] OnEndConsultarExistenciaContratista(System.IAsyncResult result) {
            long retVal = ((CYLTRACK_PHONE.VehiculoService.IVehiculoService)(this)).EndConsultarExistenciaContratista(result);
            return new object[] {
                    retVal};
        }
        
        private void OnConsultarExistenciaContratistaCompleted(object state) {
            if ((this.ConsultarExistenciaContratistaCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.ConsultarExistenciaContratistaCompleted(this, new ConsultarExistenciaContratistaCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void ConsultarExistenciaContratistaAsync(string cedula) {
            this.ConsultarExistenciaContratistaAsync(cedula, null);
        }
        
        public void ConsultarExistenciaContratistaAsync(string cedula, object userState) {
            if ((this.onBeginConsultarExistenciaContratistaDelegate == null)) {
                this.onBeginConsultarExistenciaContratistaDelegate = new BeginOperationDelegate(this.OnBeginConsultarExistenciaContratista);
            }
            if ((this.onEndConsultarExistenciaContratistaDelegate == null)) {
                this.onEndConsultarExistenciaContratistaDelegate = new EndOperationDelegate(this.OnEndConsultarExistenciaContratista);
            }
            if ((this.onConsultarExistenciaContratistaCompletedDelegate == null)) {
                this.onConsultarExistenciaContratistaCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnConsultarExistenciaContratistaCompleted);
            }
            base.InvokeAsync(this.onBeginConsultarExistenciaContratistaDelegate, new object[] {
                        cedula}, this.onEndConsultarExistenciaContratistaDelegate, this.onConsultarExistenciaContratistaCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult CYLTRACK_PHONE.VehiculoService.IVehiculoService.BeginModificar_Vehiculo(CYLTRACK_PHONE.VehiculoService.VehiculoBE vehiculo, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginModificar_Vehiculo(vehiculo, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        long CYLTRACK_PHONE.VehiculoService.IVehiculoService.EndModificar_Vehiculo(System.IAsyncResult result) {
            return base.Channel.EndModificar_Vehiculo(result);
        }
        
        private System.IAsyncResult OnBeginModificar_Vehiculo(object[] inValues, System.AsyncCallback callback, object asyncState) {
            CYLTRACK_PHONE.VehiculoService.VehiculoBE vehiculo = ((CYLTRACK_PHONE.VehiculoService.VehiculoBE)(inValues[0]));
            return ((CYLTRACK_PHONE.VehiculoService.IVehiculoService)(this)).BeginModificar_Vehiculo(vehiculo, callback, asyncState);
        }
        
        private object[] OnEndModificar_Vehiculo(System.IAsyncResult result) {
            long retVal = ((CYLTRACK_PHONE.VehiculoService.IVehiculoService)(this)).EndModificar_Vehiculo(result);
            return new object[] {
                    retVal};
        }
        
        private void OnModificar_VehiculoCompleted(object state) {
            if ((this.Modificar_VehiculoCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.Modificar_VehiculoCompleted(this, new Modificar_VehiculoCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void Modificar_VehiculoAsync(CYLTRACK_PHONE.VehiculoService.VehiculoBE vehiculo) {
            this.Modificar_VehiculoAsync(vehiculo, null);
        }
        
        public void Modificar_VehiculoAsync(CYLTRACK_PHONE.VehiculoService.VehiculoBE vehiculo, object userState) {
            if ((this.onBeginModificar_VehiculoDelegate == null)) {
                this.onBeginModificar_VehiculoDelegate = new BeginOperationDelegate(this.OnBeginModificar_Vehiculo);
            }
            if ((this.onEndModificar_VehiculoDelegate == null)) {
                this.onEndModificar_VehiculoDelegate = new EndOperationDelegate(this.OnEndModificar_Vehiculo);
            }
            if ((this.onModificar_VehiculoCompletedDelegate == null)) {
                this.onModificar_VehiculoCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnModificar_VehiculoCompleted);
            }
            base.InvokeAsync(this.onBeginModificar_VehiculoDelegate, new object[] {
                        vehiculo}, this.onEndModificar_VehiculoDelegate, this.onModificar_VehiculoCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult CYLTRACK_PHONE.VehiculoService.IVehiculoService.BeginConsultar_Conductor(string cedula, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginConsultar_Conductor(cedula, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CYLTRACK_PHONE.VehiculoService.ConductorBE CYLTRACK_PHONE.VehiculoService.IVehiculoService.EndConsultar_Conductor(System.IAsyncResult result) {
            return base.Channel.EndConsultar_Conductor(result);
        }
        
        private System.IAsyncResult OnBeginConsultar_Conductor(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string cedula = ((string)(inValues[0]));
            return ((CYLTRACK_PHONE.VehiculoService.IVehiculoService)(this)).BeginConsultar_Conductor(cedula, callback, asyncState);
        }
        
        private object[] OnEndConsultar_Conductor(System.IAsyncResult result) {
            CYLTRACK_PHONE.VehiculoService.ConductorBE retVal = ((CYLTRACK_PHONE.VehiculoService.IVehiculoService)(this)).EndConsultar_Conductor(result);
            return new object[] {
                    retVal};
        }
        
        private void OnConsultar_ConductorCompleted(object state) {
            if ((this.Consultar_ConductorCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.Consultar_ConductorCompleted(this, new Consultar_ConductorCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void Consultar_ConductorAsync(string cedula) {
            this.Consultar_ConductorAsync(cedula, null);
        }
        
        public void Consultar_ConductorAsync(string cedula, object userState) {
            if ((this.onBeginConsultar_ConductorDelegate == null)) {
                this.onBeginConsultar_ConductorDelegate = new BeginOperationDelegate(this.OnBeginConsultar_Conductor);
            }
            if ((this.onEndConsultar_ConductorDelegate == null)) {
                this.onEndConsultar_ConductorDelegate = new EndOperationDelegate(this.OnEndConsultar_Conductor);
            }
            if ((this.onConsultar_ConductorCompletedDelegate == null)) {
                this.onConsultar_ConductorCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnConsultar_ConductorCompleted);
            }
            base.InvokeAsync(this.onBeginConsultar_ConductorDelegate, new object[] {
                        cedula}, this.onEndConsultar_ConductorDelegate, this.onConsultar_ConductorCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult CYLTRACK_PHONE.VehiculoService.IVehiculoService.BeginConsultarPropVehiculo(string cedula, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginConsultarPropVehiculo(cedula, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CYLTRACK_PHONE.VehiculoService.ContratistaBE CYLTRACK_PHONE.VehiculoService.IVehiculoService.EndConsultarPropVehiculo(System.IAsyncResult result) {
            return base.Channel.EndConsultarPropVehiculo(result);
        }
        
        private System.IAsyncResult OnBeginConsultarPropVehiculo(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string cedula = ((string)(inValues[0]));
            return ((CYLTRACK_PHONE.VehiculoService.IVehiculoService)(this)).BeginConsultarPropVehiculo(cedula, callback, asyncState);
        }
        
        private object[] OnEndConsultarPropVehiculo(System.IAsyncResult result) {
            CYLTRACK_PHONE.VehiculoService.ContratistaBE retVal = ((CYLTRACK_PHONE.VehiculoService.IVehiculoService)(this)).EndConsultarPropVehiculo(result);
            return new object[] {
                    retVal};
        }
        
        private void OnConsultarPropVehiculoCompleted(object state) {
            if ((this.ConsultarPropVehiculoCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.ConsultarPropVehiculoCompleted(this, new ConsultarPropVehiculoCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void ConsultarPropVehiculoAsync(string cedula) {
            this.ConsultarPropVehiculoAsync(cedula, null);
        }
        
        public void ConsultarPropVehiculoAsync(string cedula, object userState) {
            if ((this.onBeginConsultarPropVehiculoDelegate == null)) {
                this.onBeginConsultarPropVehiculoDelegate = new BeginOperationDelegate(this.OnBeginConsultarPropVehiculo);
            }
            if ((this.onEndConsultarPropVehiculoDelegate == null)) {
                this.onEndConsultarPropVehiculoDelegate = new EndOperationDelegate(this.OnEndConsultarPropVehiculo);
            }
            if ((this.onConsultarPropVehiculoCompletedDelegate == null)) {
                this.onConsultarPropVehiculoCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnConsultarPropVehiculoCompleted);
            }
            base.InvokeAsync(this.onBeginConsultarPropVehiculoDelegate, new object[] {
                        cedula}, this.onEndConsultarPropVehiculoDelegate, this.onConsultarPropVehiculoCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult CYLTRACK_PHONE.VehiculoService.IVehiculoService.BeginRegistrarConductor(CYLTRACK_PHONE.VehiculoService.ConductorBE conductor, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginRegistrarConductor(conductor, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        long CYLTRACK_PHONE.VehiculoService.IVehiculoService.EndRegistrarConductor(System.IAsyncResult result) {
            return base.Channel.EndRegistrarConductor(result);
        }
        
        private System.IAsyncResult OnBeginRegistrarConductor(object[] inValues, System.AsyncCallback callback, object asyncState) {
            CYLTRACK_PHONE.VehiculoService.ConductorBE conductor = ((CYLTRACK_PHONE.VehiculoService.ConductorBE)(inValues[0]));
            return ((CYLTRACK_PHONE.VehiculoService.IVehiculoService)(this)).BeginRegistrarConductor(conductor, callback, asyncState);
        }
        
        private object[] OnEndRegistrarConductor(System.IAsyncResult result) {
            long retVal = ((CYLTRACK_PHONE.VehiculoService.IVehiculoService)(this)).EndRegistrarConductor(result);
            return new object[] {
                    retVal};
        }
        
        private void OnRegistrarConductorCompleted(object state) {
            if ((this.RegistrarConductorCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.RegistrarConductorCompleted(this, new RegistrarConductorCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void RegistrarConductorAsync(CYLTRACK_PHONE.VehiculoService.ConductorBE conductor) {
            this.RegistrarConductorAsync(conductor, null);
        }
        
        public void RegistrarConductorAsync(CYLTRACK_PHONE.VehiculoService.ConductorBE conductor, object userState) {
            if ((this.onBeginRegistrarConductorDelegate == null)) {
                this.onBeginRegistrarConductorDelegate = new BeginOperationDelegate(this.OnBeginRegistrarConductor);
            }
            if ((this.onEndRegistrarConductorDelegate == null)) {
                this.onEndRegistrarConductorDelegate = new EndOperationDelegate(this.OnEndRegistrarConductor);
            }
            if ((this.onRegistrarConductorCompletedDelegate == null)) {
                this.onRegistrarConductorCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnRegistrarConductorCompleted);
            }
            base.InvokeAsync(this.onBeginRegistrarConductorDelegate, new object[] {
                        conductor}, this.onEndRegistrarConductorDelegate, this.onRegistrarConductorCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult CYLTRACK_PHONE.VehiculoService.IVehiculoService.BeginRegistrarContratista(CYLTRACK_PHONE.VehiculoService.ContratistaBE contratista, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginRegistrarContratista(contratista, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        long CYLTRACK_PHONE.VehiculoService.IVehiculoService.EndRegistrarContratista(System.IAsyncResult result) {
            return base.Channel.EndRegistrarContratista(result);
        }
        
        private System.IAsyncResult OnBeginRegistrarContratista(object[] inValues, System.AsyncCallback callback, object asyncState) {
            CYLTRACK_PHONE.VehiculoService.ContratistaBE contratista = ((CYLTRACK_PHONE.VehiculoService.ContratistaBE)(inValues[0]));
            return ((CYLTRACK_PHONE.VehiculoService.IVehiculoService)(this)).BeginRegistrarContratista(contratista, callback, asyncState);
        }
        
        private object[] OnEndRegistrarContratista(System.IAsyncResult result) {
            long retVal = ((CYLTRACK_PHONE.VehiculoService.IVehiculoService)(this)).EndRegistrarContratista(result);
            return new object[] {
                    retVal};
        }
        
        private void OnRegistrarContratistaCompleted(object state) {
            if ((this.RegistrarContratistaCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.RegistrarContratistaCompleted(this, new RegistrarContratistaCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void RegistrarContratistaAsync(CYLTRACK_PHONE.VehiculoService.ContratistaBE contratista) {
            this.RegistrarContratistaAsync(contratista, null);
        }
        
        public void RegistrarContratistaAsync(CYLTRACK_PHONE.VehiculoService.ContratistaBE contratista, object userState) {
            if ((this.onBeginRegistrarContratistaDelegate == null)) {
                this.onBeginRegistrarContratistaDelegate = new BeginOperationDelegate(this.OnBeginRegistrarContratista);
            }
            if ((this.onEndRegistrarContratistaDelegate == null)) {
                this.onEndRegistrarContratistaDelegate = new EndOperationDelegate(this.OnEndRegistrarContratista);
            }
            if ((this.onRegistrarContratistaCompletedDelegate == null)) {
                this.onRegistrarContratistaCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnRegistrarContratistaCompleted);
            }
            base.InvokeAsync(this.onBeginRegistrarContratistaDelegate, new object[] {
                        contratista}, this.onEndRegistrarContratistaDelegate, this.onRegistrarContratistaCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult CYLTRACK_PHONE.VehiculoService.IVehiculoService.BeginConsultarExistenciaConductor(string cedula, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginConsultarExistenciaConductor(cedula, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        long CYLTRACK_PHONE.VehiculoService.IVehiculoService.EndConsultarExistenciaConductor(System.IAsyncResult result) {
            return base.Channel.EndConsultarExistenciaConductor(result);
        }
        
        private System.IAsyncResult OnBeginConsultarExistenciaConductor(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string cedula = ((string)(inValues[0]));
            return ((CYLTRACK_PHONE.VehiculoService.IVehiculoService)(this)).BeginConsultarExistenciaConductor(cedula, callback, asyncState);
        }
        
        private object[] OnEndConsultarExistenciaConductor(System.IAsyncResult result) {
            long retVal = ((CYLTRACK_PHONE.VehiculoService.IVehiculoService)(this)).EndConsultarExistenciaConductor(result);
            return new object[] {
                    retVal};
        }
        
        private void OnConsultarExistenciaConductorCompleted(object state) {
            if ((this.ConsultarExistenciaConductorCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.ConsultarExistenciaConductorCompleted(this, new ConsultarExistenciaConductorCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void ConsultarExistenciaConductorAsync(string cedula) {
            this.ConsultarExistenciaConductorAsync(cedula, null);
        }
        
        public void ConsultarExistenciaConductorAsync(string cedula, object userState) {
            if ((this.onBeginConsultarExistenciaConductorDelegate == null)) {
                this.onBeginConsultarExistenciaConductorDelegate = new BeginOperationDelegate(this.OnBeginConsultarExistenciaConductor);
            }
            if ((this.onEndConsultarExistenciaConductorDelegate == null)) {
                this.onEndConsultarExistenciaConductorDelegate = new EndOperationDelegate(this.OnEndConsultarExistenciaConductor);
            }
            if ((this.onConsultarExistenciaConductorCompletedDelegate == null)) {
                this.onConsultarExistenciaConductorCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnConsultarExistenciaConductorCompleted);
            }
            base.InvokeAsync(this.onBeginConsultarExistenciaConductorDelegate, new object[] {
                        cedula}, this.onEndConsultarExistenciaConductorDelegate, this.onConsultarExistenciaConductorCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginOpen(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(callback, asyncState);
        }
        
        private object[] OnEndOpen(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndOpen(result);
            return null;
        }
        
        private void OnOpenCompleted(object state) {
            if ((this.OpenCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.OpenCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void OpenAsync() {
            this.OpenAsync(null);
        }
        
        public void OpenAsync(object userState) {
            if ((this.onBeginOpenDelegate == null)) {
                this.onBeginOpenDelegate = new BeginOperationDelegate(this.OnBeginOpen);
            }
            if ((this.onEndOpenDelegate == null)) {
                this.onEndOpenDelegate = new EndOperationDelegate(this.OnEndOpen);
            }
            if ((this.onOpenCompletedDelegate == null)) {
                this.onOpenCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnOpenCompleted);
            }
            base.InvokeAsync(this.onBeginOpenDelegate, null, this.onEndOpenDelegate, this.onOpenCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginClose(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginClose(callback, asyncState);
        }
        
        private object[] OnEndClose(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndClose(result);
            return null;
        }
        
        private void OnCloseCompleted(object state) {
            if ((this.CloseCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.CloseCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void CloseAsync() {
            this.CloseAsync(null);
        }
        
        public void CloseAsync(object userState) {
            if ((this.onBeginCloseDelegate == null)) {
                this.onBeginCloseDelegate = new BeginOperationDelegate(this.OnBeginClose);
            }
            if ((this.onEndCloseDelegate == null)) {
                this.onEndCloseDelegate = new EndOperationDelegate(this.OnEndClose);
            }
            if ((this.onCloseCompletedDelegate == null)) {
                this.onCloseCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCloseCompleted);
            }
            base.InvokeAsync(this.onBeginCloseDelegate, null, this.onEndCloseDelegate, this.onCloseCompletedDelegate, userState);
        }
        
        protected override CYLTRACK_PHONE.VehiculoService.IVehiculoService CreateChannel() {
            return new VehiculoServiceClientChannel(this);
        }
        
        private class VehiculoServiceClientChannel : ChannelBase<CYLTRACK_PHONE.VehiculoService.IVehiculoService>, CYLTRACK_PHONE.VehiculoService.IVehiculoService {
            
            public VehiculoServiceClientChannel(System.ServiceModel.ClientBase<CYLTRACK_PHONE.VehiculoService.IVehiculoService> client) : 
                    base(client) {
            }
            
            public System.IAsyncResult BeginRegistrar_Vehiculo(CYLTRACK_PHONE.VehiculoService.VehiculoBE vehiculo, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = vehiculo;
                System.IAsyncResult _result = base.BeginInvoke("Registrar_Vehiculo", _args, callback, asyncState);
                return _result;
            }
            
            public long EndRegistrar_Vehiculo(System.IAsyncResult result) {
                object[] _args = new object[0];
                long _result = ((long)(base.EndInvoke("Registrar_Vehiculo", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginConsultarVehiculo(string placa, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = placa;
                System.IAsyncResult _result = base.BeginInvoke("ConsultarVehiculo", _args, callback, asyncState);
                return _result;
            }
            
            public System.Collections.ObjectModel.ObservableCollection<CYLTRACK_PHONE.VehiculoService.VehiculoBE> EndConsultarVehiculo(System.IAsyncResult result) {
                object[] _args = new object[0];
                System.Collections.ObjectModel.ObservableCollection<CYLTRACK_PHONE.VehiculoService.VehiculoBE> _result = ((System.Collections.ObjectModel.ObservableCollection<CYLTRACK_PHONE.VehiculoService.VehiculoBE>)(base.EndInvoke("ConsultarVehiculo", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginConsultarExistenciaVehiculo(string placa, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = placa;
                System.IAsyncResult _result = base.BeginInvoke("ConsultarExistenciaVehiculo", _args, callback, asyncState);
                return _result;
            }
            
            public long EndConsultarExistenciaVehiculo(System.IAsyncResult result) {
                object[] _args = new object[0];
                long _result = ((long)(base.EndInvoke("ConsultarExistenciaVehiculo", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginConsultarExistenciaContratista(string cedula, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = cedula;
                System.IAsyncResult _result = base.BeginInvoke("ConsultarExistenciaContratista", _args, callback, asyncState);
                return _result;
            }
            
            public long EndConsultarExistenciaContratista(System.IAsyncResult result) {
                object[] _args = new object[0];
                long _result = ((long)(base.EndInvoke("ConsultarExistenciaContratista", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginModificar_Vehiculo(CYLTRACK_PHONE.VehiculoService.VehiculoBE vehiculo, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = vehiculo;
                System.IAsyncResult _result = base.BeginInvoke("Modificar_Vehiculo", _args, callback, asyncState);
                return _result;
            }
            
            public long EndModificar_Vehiculo(System.IAsyncResult result) {
                object[] _args = new object[0];
                long _result = ((long)(base.EndInvoke("Modificar_Vehiculo", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginConsultar_Conductor(string cedula, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = cedula;
                System.IAsyncResult _result = base.BeginInvoke("Consultar_Conductor", _args, callback, asyncState);
                return _result;
            }
            
            public CYLTRACK_PHONE.VehiculoService.ConductorBE EndConsultar_Conductor(System.IAsyncResult result) {
                object[] _args = new object[0];
                CYLTRACK_PHONE.VehiculoService.ConductorBE _result = ((CYLTRACK_PHONE.VehiculoService.ConductorBE)(base.EndInvoke("Consultar_Conductor", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginConsultarPropVehiculo(string cedula, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = cedula;
                System.IAsyncResult _result = base.BeginInvoke("ConsultarPropVehiculo", _args, callback, asyncState);
                return _result;
            }
            
            public CYLTRACK_PHONE.VehiculoService.ContratistaBE EndConsultarPropVehiculo(System.IAsyncResult result) {
                object[] _args = new object[0];
                CYLTRACK_PHONE.VehiculoService.ContratistaBE _result = ((CYLTRACK_PHONE.VehiculoService.ContratistaBE)(base.EndInvoke("ConsultarPropVehiculo", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginRegistrarConductor(CYLTRACK_PHONE.VehiculoService.ConductorBE conductor, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = conductor;
                System.IAsyncResult _result = base.BeginInvoke("RegistrarConductor", _args, callback, asyncState);
                return _result;
            }
            
            public long EndRegistrarConductor(System.IAsyncResult result) {
                object[] _args = new object[0];
                long _result = ((long)(base.EndInvoke("RegistrarConductor", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginRegistrarContratista(CYLTRACK_PHONE.VehiculoService.ContratistaBE contratista, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = contratista;
                System.IAsyncResult _result = base.BeginInvoke("RegistrarContratista", _args, callback, asyncState);
                return _result;
            }
            
            public long EndRegistrarContratista(System.IAsyncResult result) {
                object[] _args = new object[0];
                long _result = ((long)(base.EndInvoke("RegistrarContratista", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginConsultarExistenciaConductor(string cedula, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = cedula;
                System.IAsyncResult _result = base.BeginInvoke("ConsultarExistenciaConductor", _args, callback, asyncState);
                return _result;
            }
            
            public long EndConsultarExistenciaConductor(System.IAsyncResult result) {
                object[] _args = new object[0];
                long _result = ((long)(base.EndInvoke("ConsultarExistenciaConductor", _args, result)));
                return _result;
            }
        }
    }
}
