//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.18444
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CYLTRACK_WebApp.VehiculoService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://servicios.cyltrack.com.co/cyltrack/", ConfigurationName="VehiculoService.IVehiculoService")]
    public interface IVehiculoService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://servicios.cyltrack.com.co/cyltrack/IVehiculoService/Registrar_Vehiculo", ReplyAction="http://servicios.cyltrack.com.co/cyltrack/IVehiculoService/Registrar_VehiculoResp" +
            "onse")]
        long Registrar_Vehiculo(Unisangil.CYLTRACK.CYLTRACK_BE.VehiculoBE vehiculo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://servicios.cyltrack.com.co/cyltrack/IVehiculoService/ConsultarVehiculo", ReplyAction="http://servicios.cyltrack.com.co/cyltrack/IVehiculoService/ConsultarVehiculoRespo" +
            "nse")]
        Unisangil.CYLTRACK.CYLTRACK_BE.VehiculoBE[] ConsultarVehiculo(string placa);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://servicios.cyltrack.com.co/cyltrack/IVehiculoService/ConsultarExistenciaVeh" +
            "iculo", ReplyAction="http://servicios.cyltrack.com.co/cyltrack/IVehiculoService/ConsultarExistenciaVeh" +
            "iculoResponse")]
        long ConsultarExistenciaVehiculo(string placa);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://servicios.cyltrack.com.co/cyltrack/IVehiculoService/ConsultarExistenciaCon" +
            "tratista", ReplyAction="http://servicios.cyltrack.com.co/cyltrack/IVehiculoService/ConsultarExistenciaCon" +
            "tratistaResponse")]
        long ConsultarExistenciaContratista(string cedula);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://servicios.cyltrack.com.co/cyltrack/IVehiculoService/Modificar_Vehiculo", ReplyAction="http://servicios.cyltrack.com.co/cyltrack/IVehiculoService/Modificar_VehiculoResp" +
            "onse")]
        long Modificar_Vehiculo(Unisangil.CYLTRACK.CYLTRACK_BE.VehiculoBE vehiculo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://servicios.cyltrack.com.co/cyltrack/IVehiculoService/Consultar_Conductor", ReplyAction="http://servicios.cyltrack.com.co/cyltrack/IVehiculoService/Consultar_ConductorRes" +
            "ponse")]
        Unisangil.CYLTRACK.CYLTRACK_BE.ConductorBE Consultar_Conductor(string cedula);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://servicios.cyltrack.com.co/cyltrack/IVehiculoService/ConsultarPropVehiculo", ReplyAction="http://servicios.cyltrack.com.co/cyltrack/IVehiculoService/ConsultarPropVehiculoR" +
            "esponse")]
        Unisangil.CYLTRACK.CYLTRACK_BE.ContratistaBE ConsultarPropVehiculo(string cedula);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://servicios.cyltrack.com.co/cyltrack/IVehiculoService/RegistrarConductor", ReplyAction="http://servicios.cyltrack.com.co/cyltrack/IVehiculoService/RegistrarConductorResp" +
            "onse")]
        long RegistrarConductor(Unisangil.CYLTRACK.CYLTRACK_BE.ConductorBE conductor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://servicios.cyltrack.com.co/cyltrack/IVehiculoService/RegistrarContratista", ReplyAction="http://servicios.cyltrack.com.co/cyltrack/IVehiculoService/RegistrarContratistaRe" +
            "sponse")]
        long RegistrarContratista(Unisangil.CYLTRACK.CYLTRACK_BE.ContratistaBE contratista);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://servicios.cyltrack.com.co/cyltrack/IVehiculoService/ConsultarExistenciaCon" +
            "ductor", ReplyAction="http://servicios.cyltrack.com.co/cyltrack/IVehiculoService/ConsultarExistenciaCon" +
            "ductorResponse")]
        long ConsultarExistenciaConductor(string cedula);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IVehiculoServiceChannel : CYLTRACK_WebApp.VehiculoService.IVehiculoService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class VehiculoServiceClient : System.ServiceModel.ClientBase<CYLTRACK_WebApp.VehiculoService.IVehiculoService>, CYLTRACK_WebApp.VehiculoService.IVehiculoService {
        
        public VehiculoServiceClient() {
        }
        
        public VehiculoServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public VehiculoServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public VehiculoServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public VehiculoServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public long Registrar_Vehiculo(Unisangil.CYLTRACK.CYLTRACK_BE.VehiculoBE vehiculo) {
            return base.Channel.Registrar_Vehiculo(vehiculo);
        }
        
        public Unisangil.CYLTRACK.CYLTRACK_BE.VehiculoBE[] ConsultarVehiculo(string placa) {
            return base.Channel.ConsultarVehiculo(placa);
        }
        
        public long ConsultarExistenciaVehiculo(string placa) {
            return base.Channel.ConsultarExistenciaVehiculo(placa);
        }
        
        public long ConsultarExistenciaContratista(string cedula) {
            return base.Channel.ConsultarExistenciaContratista(cedula);
        }
        
        public long Modificar_Vehiculo(Unisangil.CYLTRACK.CYLTRACK_BE.VehiculoBE vehiculo) {
            return base.Channel.Modificar_Vehiculo(vehiculo);
        }
        
        public Unisangil.CYLTRACK.CYLTRACK_BE.ConductorBE Consultar_Conductor(string cedula) {
            return base.Channel.Consultar_Conductor(cedula);
        }
        
        public Unisangil.CYLTRACK.CYLTRACK_BE.ContratistaBE ConsultarPropVehiculo(string cedula) {
            return base.Channel.ConsultarPropVehiculo(cedula);
        }
        
        public long RegistrarConductor(Unisangil.CYLTRACK.CYLTRACK_BE.ConductorBE conductor) {
            return base.Channel.RegistrarConductor(conductor);
        }
        
        public long RegistrarContratista(Unisangil.CYLTRACK.CYLTRACK_BE.ContratistaBE contratista) {
            return base.Channel.RegistrarContratista(contratista);
        }
        
        public long ConsultarExistenciaConductor(string cedula) {
            return base.Channel.ConsultarExistenciaConductor(cedula);
        }
    }
}
