//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.235
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CYLTRACK_WebApp.PedidoService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://servicios.cyltrack.com.co/cyltrack/", ConfigurationName="PedidoService.IPedidoService")]
    public interface IPedidoService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://servicios.cyltrack.com.co/cyltrack/IPedidoService/Registrar_Pedido", ReplyAction="http://servicios.cyltrack.com.co/cyltrack/IPedidoService/Registrar_PedidoResponse" +
            "")]
        string Registrar_Pedido(Unisangil.CYLTRACK.CYLTRACK_BE.PedidoBE pedido);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://servicios.cyltrack.com.co/cyltrack/IPedidoService/Consultar_Pedido", ReplyAction="http://servicios.cyltrack.com.co/cyltrack/IPedidoService/Consultar_PedidoResponse" +
            "")]
        Unisangil.CYLTRACK.CYLTRACK_BE.PedidoBE Consultar_Pedido(string pedido);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://servicios.cyltrack.com.co/cyltrack/IPedidoService/Consultar_Existencia", ReplyAction="http://servicios.cyltrack.com.co/cyltrack/IPedidoService/Consultar_ExistenciaResp" +
            "onse")]
        string Consultar_Existencia([System.ServiceModel.MessageParameterAttribute(Name="consultar_existencia")] string consultar_existencia1);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://servicios.cyltrack.com.co/cyltrack/IPedidoService/Modificar_Pedido", ReplyAction="http://servicios.cyltrack.com.co/cyltrack/IPedidoService/Modificar_PedidoResponse" +
            "")]
        string Modificar_Pedido(string pedido);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://servicios.cyltrack.com.co/cyltrack/IPedidoService/Cancelar_Pedido", ReplyAction="http://servicios.cyltrack.com.co/cyltrack/IPedidoService/Cancelar_PedidoResponse")]
        string Cancelar_Pedido(string pedido);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IPedidoServiceChannel : CYLTRACK_WebApp.PedidoService.IPedidoService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PedidoServiceClient : System.ServiceModel.ClientBase<CYLTRACK_WebApp.PedidoService.IPedidoService>, CYLTRACK_WebApp.PedidoService.IPedidoService {
        
        public PedidoServiceClient() {
        }
        
        public PedidoServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PedidoServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PedidoServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PedidoServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string Registrar_Pedido(Unisangil.CYLTRACK.CYLTRACK_BE.PedidoBE pedido) {
            return base.Channel.Registrar_Pedido(pedido);
        }
        
        public Unisangil.CYLTRACK.CYLTRACK_BE.PedidoBE Consultar_Pedido(string pedido) {
            return base.Channel.Consultar_Pedido(pedido);
        }
        
        public string Consultar_Existencia(string consultar_existencia1) {
            return base.Channel.Consultar_Existencia(consultar_existencia1);
        }
        
        public string Modificar_Pedido(string pedido) {
            return base.Channel.Modificar_Pedido(pedido);
        }
        
        public string Cancelar_Pedido(string pedido) {
            return base.Channel.Cancelar_Pedido(pedido);
        }
    }
}
