//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.18444
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This code was auto-generated by Microsoft.Silverlight.Phone.ServiceReference, version 3.7.0.0
// 
namespace CYLTRACK_PHONE.VentaService {
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="VentaBE", Namespace="http://schemas.datacontract.org/2004/07/Unisangil.CYLTRACK.CYLTRACK_BE")]
    public partial class VentaBE : object, System.ComponentModel.INotifyPropertyChanged {
        
        private CYLTRACK_PHONE.VentaService.Detalle_VentaBE Detalle_VentaField;
        
        private System.DateTime FechaField;
        
        private string IdClienteField;
        
        private string IdVehiculoField;
        
        private string Id_UbicacionField;
        
        private string Id_VentaField;
        
        private System.Collections.ObjectModel.ObservableCollection<CYLTRACK_PHONE.VentaService.Detalle_VentaBE> Lista_Detalle_VentaField;
        
        private string ObservacionesField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CYLTRACK_PHONE.VentaService.Detalle_VentaBE Detalle_Venta {
            get {
                return this.Detalle_VentaField;
            }
            set {
                if ((object.ReferenceEquals(this.Detalle_VentaField, value) != true)) {
                    this.Detalle_VentaField = value;
                    this.RaisePropertyChanged("Detalle_Venta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Fecha {
            get {
                return this.FechaField;
            }
            set {
                if ((this.FechaField.Equals(value) != true)) {
                    this.FechaField = value;
                    this.RaisePropertyChanged("Fecha");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IdCliente {
            get {
                return this.IdClienteField;
            }
            set {
                if ((object.ReferenceEquals(this.IdClienteField, value) != true)) {
                    this.IdClienteField = value;
                    this.RaisePropertyChanged("IdCliente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IdVehiculo {
            get {
                return this.IdVehiculoField;
            }
            set {
                if ((object.ReferenceEquals(this.IdVehiculoField, value) != true)) {
                    this.IdVehiculoField = value;
                    this.RaisePropertyChanged("IdVehiculo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Id_Ubicacion {
            get {
                return this.Id_UbicacionField;
            }
            set {
                if ((object.ReferenceEquals(this.Id_UbicacionField, value) != true)) {
                    this.Id_UbicacionField = value;
                    this.RaisePropertyChanged("Id_Ubicacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Id_Venta {
            get {
                return this.Id_VentaField;
            }
            set {
                if ((object.ReferenceEquals(this.Id_VentaField, value) != true)) {
                    this.Id_VentaField = value;
                    this.RaisePropertyChanged("Id_Venta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.ObjectModel.ObservableCollection<CYLTRACK_PHONE.VentaService.Detalle_VentaBE> Lista_Detalle_Venta {
            get {
                return this.Lista_Detalle_VentaField;
            }
            set {
                if ((object.ReferenceEquals(this.Lista_Detalle_VentaField, value) != true)) {
                    this.Lista_Detalle_VentaField = value;
                    this.RaisePropertyChanged("Lista_Detalle_Venta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Observaciones {
            get {
                return this.ObservacionesField;
            }
            set {
                if ((object.ReferenceEquals(this.ObservacionesField, value) != true)) {
                    this.ObservacionesField = value;
                    this.RaisePropertyChanged("Observaciones");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Detalle_VentaBE", Namespace="http://schemas.datacontract.org/2004/07/Unisangil.CYLTRACK.CYLTRACK_BE")]
    public partial class Detalle_VentaBE : object, System.ComponentModel.INotifyPropertyChanged {
        
        private CYLTRACK_PHONE.VentaService.CasosBE Casos_EspecialesField;
        
        private string IdVentaField;
        
        private string Id_Cilindro_EntradaField;
        
        private string Id_Cilindro_SalidaField;
        
        private string Id_Detalle_VentaField;
        
        private string Id_UbicacionField;
        
        private string Id_VehiculoField;
        
        private string TamanoField;
        
        private string Tipo_CilindroField;
        
        private string Tipo_VentaField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CYLTRACK_PHONE.VentaService.CasosBE Casos_Especiales {
            get {
                return this.Casos_EspecialesField;
            }
            set {
                if ((object.ReferenceEquals(this.Casos_EspecialesField, value) != true)) {
                    this.Casos_EspecialesField = value;
                    this.RaisePropertyChanged("Casos_Especiales");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IdVenta {
            get {
                return this.IdVentaField;
            }
            set {
                if ((object.ReferenceEquals(this.IdVentaField, value) != true)) {
                    this.IdVentaField = value;
                    this.RaisePropertyChanged("IdVenta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Id_Cilindro_Entrada {
            get {
                return this.Id_Cilindro_EntradaField;
            }
            set {
                if ((object.ReferenceEquals(this.Id_Cilindro_EntradaField, value) != true)) {
                    this.Id_Cilindro_EntradaField = value;
                    this.RaisePropertyChanged("Id_Cilindro_Entrada");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Id_Cilindro_Salida {
            get {
                return this.Id_Cilindro_SalidaField;
            }
            set {
                if ((object.ReferenceEquals(this.Id_Cilindro_SalidaField, value) != true)) {
                    this.Id_Cilindro_SalidaField = value;
                    this.RaisePropertyChanged("Id_Cilindro_Salida");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Id_Detalle_Venta {
            get {
                return this.Id_Detalle_VentaField;
            }
            set {
                if ((object.ReferenceEquals(this.Id_Detalle_VentaField, value) != true)) {
                    this.Id_Detalle_VentaField = value;
                    this.RaisePropertyChanged("Id_Detalle_Venta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Id_Ubicacion {
            get {
                return this.Id_UbicacionField;
            }
            set {
                if ((object.ReferenceEquals(this.Id_UbicacionField, value) != true)) {
                    this.Id_UbicacionField = value;
                    this.RaisePropertyChanged("Id_Ubicacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Id_Vehiculo {
            get {
                return this.Id_VehiculoField;
            }
            set {
                if ((object.ReferenceEquals(this.Id_VehiculoField, value) != true)) {
                    this.Id_VehiculoField = value;
                    this.RaisePropertyChanged("Id_Vehiculo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Tamano {
            get {
                return this.TamanoField;
            }
            set {
                if ((object.ReferenceEquals(this.TamanoField, value) != true)) {
                    this.TamanoField = value;
                    this.RaisePropertyChanged("Tamano");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Tipo_Cilindro {
            get {
                return this.Tipo_CilindroField;
            }
            set {
                if ((object.ReferenceEquals(this.Tipo_CilindroField, value) != true)) {
                    this.Tipo_CilindroField = value;
                    this.RaisePropertyChanged("Tipo_Cilindro");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Tipo_Venta {
            get {
                return this.Tipo_VentaField;
            }
            set {
                if ((object.ReferenceEquals(this.Tipo_VentaField, value) != true)) {
                    this.Tipo_VentaField = value;
                    this.RaisePropertyChanged("Tipo_Venta");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CasosBE", Namespace="http://schemas.datacontract.org/2004/07/Unisangil.CYLTRACK.CYLTRACK_BE")]
    public partial class CasosBE : object, System.ComponentModel.INotifyPropertyChanged {
        
        private CYLTRACK_PHONE.VentaService.Detalle_VentaBE Detalle_VentaField;
        
        private string EstadoCasoField;
        
        private string Id_CasosField;
        
        private string Id_ClienteField;
        
        private string ObservacionesField;
        
        private CYLTRACK_PHONE.VentaService.Tipo_CasoBE Tipo_CasoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CYLTRACK_PHONE.VentaService.Detalle_VentaBE Detalle_Venta {
            get {
                return this.Detalle_VentaField;
            }
            set {
                if ((object.ReferenceEquals(this.Detalle_VentaField, value) != true)) {
                    this.Detalle_VentaField = value;
                    this.RaisePropertyChanged("Detalle_Venta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EstadoCaso {
            get {
                return this.EstadoCasoField;
            }
            set {
                if ((object.ReferenceEquals(this.EstadoCasoField, value) != true)) {
                    this.EstadoCasoField = value;
                    this.RaisePropertyChanged("EstadoCaso");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Id_Casos {
            get {
                return this.Id_CasosField;
            }
            set {
                if ((object.ReferenceEquals(this.Id_CasosField, value) != true)) {
                    this.Id_CasosField = value;
                    this.RaisePropertyChanged("Id_Casos");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Id_Cliente {
            get {
                return this.Id_ClienteField;
            }
            set {
                if ((object.ReferenceEquals(this.Id_ClienteField, value) != true)) {
                    this.Id_ClienteField = value;
                    this.RaisePropertyChanged("Id_Cliente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Observaciones {
            get {
                return this.ObservacionesField;
            }
            set {
                if ((object.ReferenceEquals(this.ObservacionesField, value) != true)) {
                    this.ObservacionesField = value;
                    this.RaisePropertyChanged("Observaciones");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CYLTRACK_PHONE.VentaService.Tipo_CasoBE Tipo_Caso {
            get {
                return this.Tipo_CasoField;
            }
            set {
                if ((object.ReferenceEquals(this.Tipo_CasoField, value) != true)) {
                    this.Tipo_CasoField = value;
                    this.RaisePropertyChanged("Tipo_Caso");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Tipo_CasoBE", Namespace="http://schemas.datacontract.org/2004/07/Unisangil.CYLTRACK.CYLTRACK_BE")]
    public partial class Tipo_CasoBE : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string Descripcion_Tipo_CasoField;
        
        private string Id_Tipo_CasoField;
        
        private string Nombre_CasoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descripcion_Tipo_Caso {
            get {
                return this.Descripcion_Tipo_CasoField;
            }
            set {
                if ((object.ReferenceEquals(this.Descripcion_Tipo_CasoField, value) != true)) {
                    this.Descripcion_Tipo_CasoField = value;
                    this.RaisePropertyChanged("Descripcion_Tipo_Caso");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Id_Tipo_Caso {
            get {
                return this.Id_Tipo_CasoField;
            }
            set {
                if ((object.ReferenceEquals(this.Id_Tipo_CasoField, value) != true)) {
                    this.Id_Tipo_CasoField = value;
                    this.RaisePropertyChanged("Id_Tipo_Caso");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre_Caso {
            get {
                return this.Nombre_CasoField;
            }
            set {
                if ((object.ReferenceEquals(this.Nombre_CasoField, value) != true)) {
                    this.Nombre_CasoField = value;
                    this.RaisePropertyChanged("Nombre_Caso");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://servicios.cyltrack.com.co/cyltrack/", ConfigurationName="VentaService.IVentaService")]
    public interface IVentaService {
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://servicios.cyltrack.com.co/cyltrack/IVentaService/RegistrarVenta", ReplyAction="http://servicios.cyltrack.com.co/cyltrack/IVentaService/RegistrarVentaResponse")]
        System.IAsyncResult BeginRegistrarVenta(CYLTRACK_PHONE.VentaService.VentaBE ventas, System.AsyncCallback callback, object asyncState);
        
        long EndRegistrarVenta(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://servicios.cyltrack.com.co/cyltrack/IVentaService/ConsultarExistenciaVenta", ReplyAction="http://servicios.cyltrack.com.co/cyltrack/IVentaService/ConsultarExistenciaVentaR" +
            "esponse")]
        System.IAsyncResult BeginConsultarExistenciaVenta(string ventas, System.AsyncCallback callback, object asyncState);
        
        long EndConsultarExistenciaVenta(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://servicios.cyltrack.com.co/cyltrack/IVentaService/ConsultarVenta", ReplyAction="http://servicios.cyltrack.com.co/cyltrack/IVentaService/ConsultarVentaResponse")]
        System.IAsyncResult BeginConsultarVenta(string datoConsulta, System.AsyncCallback callback, object asyncState);
        
        CYLTRACK_PHONE.VentaService.VentaBE EndConsultarVenta(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://servicios.cyltrack.com.co/cyltrack/IVentaService/RevisionCasosEspeciales", ReplyAction="http://servicios.cyltrack.com.co/cyltrack/IVentaService/RevisionCasosEspecialesRe" +
            "sponse")]
        System.IAsyncResult BeginRevisionCasosEspeciales(string casos, System.AsyncCallback callback, object asyncState);
        
        System.Collections.ObjectModel.ObservableCollection<CYLTRACK_PHONE.VentaService.CasosBE> EndRevisionCasosEspeciales(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://servicios.cyltrack.com.co/cyltrack/IVentaService/CasosEspeciales", ReplyAction="http://servicios.cyltrack.com.co/cyltrack/IVentaService/CasosEspecialesResponse")]
        System.IAsyncResult BeginCasosEspeciales(CYLTRACK_PHONE.VentaService.CasosBE casos, System.AsyncCallback callback, object asyncState);
        
        long EndCasosEspeciales(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://servicios.cyltrack.com.co/cyltrack/IVentaService/ModificarVenta", ReplyAction="http://servicios.cyltrack.com.co/cyltrack/IVentaService/ModificarVentaResponse")]
        System.IAsyncResult BeginModificarVenta(CYLTRACK_PHONE.VentaService.Detalle_VentaBE detVenta, System.AsyncCallback callback, object asyncState);
        
        long EndModificarVenta(System.IAsyncResult result);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IVentaServiceChannel : CYLTRACK_PHONE.VentaService.IVentaService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RegistrarVentaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public RegistrarVentaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public long Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((long)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ConsultarExistenciaVentaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public ConsultarExistenciaVentaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public long Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((long)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ConsultarVentaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public ConsultarVentaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public CYLTRACK_PHONE.VentaService.VentaBE Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((CYLTRACK_PHONE.VentaService.VentaBE)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RevisionCasosEspecialesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public RevisionCasosEspecialesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public System.Collections.ObjectModel.ObservableCollection<CYLTRACK_PHONE.VentaService.CasosBE> Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((System.Collections.ObjectModel.ObservableCollection<CYLTRACK_PHONE.VentaService.CasosBE>)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CasosEspecialesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public CasosEspecialesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public long Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((long)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ModificarVentaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public ModificarVentaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public long Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((long)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class VentaServiceClient : System.ServiceModel.ClientBase<CYLTRACK_PHONE.VentaService.IVentaService>, CYLTRACK_PHONE.VentaService.IVentaService {
        
        private BeginOperationDelegate onBeginRegistrarVentaDelegate;
        
        private EndOperationDelegate onEndRegistrarVentaDelegate;
        
        private System.Threading.SendOrPostCallback onRegistrarVentaCompletedDelegate;
        
        private BeginOperationDelegate onBeginConsultarExistenciaVentaDelegate;
        
        private EndOperationDelegate onEndConsultarExistenciaVentaDelegate;
        
        private System.Threading.SendOrPostCallback onConsultarExistenciaVentaCompletedDelegate;
        
        private BeginOperationDelegate onBeginConsultarVentaDelegate;
        
        private EndOperationDelegate onEndConsultarVentaDelegate;
        
        private System.Threading.SendOrPostCallback onConsultarVentaCompletedDelegate;
        
        private BeginOperationDelegate onBeginRevisionCasosEspecialesDelegate;
        
        private EndOperationDelegate onEndRevisionCasosEspecialesDelegate;
        
        private System.Threading.SendOrPostCallback onRevisionCasosEspecialesCompletedDelegate;
        
        private BeginOperationDelegate onBeginCasosEspecialesDelegate;
        
        private EndOperationDelegate onEndCasosEspecialesDelegate;
        
        private System.Threading.SendOrPostCallback onCasosEspecialesCompletedDelegate;
        
        private BeginOperationDelegate onBeginModificarVentaDelegate;
        
        private EndOperationDelegate onEndModificarVentaDelegate;
        
        private System.Threading.SendOrPostCallback onModificarVentaCompletedDelegate;
        
        private BeginOperationDelegate onBeginOpenDelegate;
        
        private EndOperationDelegate onEndOpenDelegate;
        
        private System.Threading.SendOrPostCallback onOpenCompletedDelegate;
        
        private BeginOperationDelegate onBeginCloseDelegate;
        
        private EndOperationDelegate onEndCloseDelegate;
        
        private System.Threading.SendOrPostCallback onCloseCompletedDelegate;
        
        public VentaServiceClient() {
        }
        
        public VentaServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public VentaServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public VentaServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public VentaServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Net.CookieContainer CookieContainer {
            get {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    return httpCookieContainerManager.CookieContainer;
                }
                else {
                    return null;
                }
            }
            set {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    httpCookieContainerManager.CookieContainer = value;
                }
                else {
                    throw new System.InvalidOperationException("Unable to set the CookieContainer. Please make sure the binding contains an HttpC" +
                            "ookieContainerBindingElement.");
                }
            }
        }
        
        public event System.EventHandler<RegistrarVentaCompletedEventArgs> RegistrarVentaCompleted;
        
        public event System.EventHandler<ConsultarExistenciaVentaCompletedEventArgs> ConsultarExistenciaVentaCompleted;
        
        public event System.EventHandler<ConsultarVentaCompletedEventArgs> ConsultarVentaCompleted;
        
        public event System.EventHandler<RevisionCasosEspecialesCompletedEventArgs> RevisionCasosEspecialesCompleted;
        
        public event System.EventHandler<CasosEspecialesCompletedEventArgs> CasosEspecialesCompleted;
        
        public event System.EventHandler<ModificarVentaCompletedEventArgs> ModificarVentaCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> OpenCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> CloseCompleted;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult CYLTRACK_PHONE.VentaService.IVentaService.BeginRegistrarVenta(CYLTRACK_PHONE.VentaService.VentaBE ventas, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginRegistrarVenta(ventas, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        long CYLTRACK_PHONE.VentaService.IVentaService.EndRegistrarVenta(System.IAsyncResult result) {
            return base.Channel.EndRegistrarVenta(result);
        }
        
        private System.IAsyncResult OnBeginRegistrarVenta(object[] inValues, System.AsyncCallback callback, object asyncState) {
            CYLTRACK_PHONE.VentaService.VentaBE ventas = ((CYLTRACK_PHONE.VentaService.VentaBE)(inValues[0]));
            return ((CYLTRACK_PHONE.VentaService.IVentaService)(this)).BeginRegistrarVenta(ventas, callback, asyncState);
        }
        
        private object[] OnEndRegistrarVenta(System.IAsyncResult result) {
            long retVal = ((CYLTRACK_PHONE.VentaService.IVentaService)(this)).EndRegistrarVenta(result);
            return new object[] {
                    retVal};
        }
        
        private void OnRegistrarVentaCompleted(object state) {
            if ((this.RegistrarVentaCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.RegistrarVentaCompleted(this, new RegistrarVentaCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void RegistrarVentaAsync(CYLTRACK_PHONE.VentaService.VentaBE ventas) {
            this.RegistrarVentaAsync(ventas, null);
        }
        
        public void RegistrarVentaAsync(CYLTRACK_PHONE.VentaService.VentaBE ventas, object userState) {
            if ((this.onBeginRegistrarVentaDelegate == null)) {
                this.onBeginRegistrarVentaDelegate = new BeginOperationDelegate(this.OnBeginRegistrarVenta);
            }
            if ((this.onEndRegistrarVentaDelegate == null)) {
                this.onEndRegistrarVentaDelegate = new EndOperationDelegate(this.OnEndRegistrarVenta);
            }
            if ((this.onRegistrarVentaCompletedDelegate == null)) {
                this.onRegistrarVentaCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnRegistrarVentaCompleted);
            }
            base.InvokeAsync(this.onBeginRegistrarVentaDelegate, new object[] {
                        ventas}, this.onEndRegistrarVentaDelegate, this.onRegistrarVentaCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult CYLTRACK_PHONE.VentaService.IVentaService.BeginConsultarExistenciaVenta(string ventas, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginConsultarExistenciaVenta(ventas, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        long CYLTRACK_PHONE.VentaService.IVentaService.EndConsultarExistenciaVenta(System.IAsyncResult result) {
            return base.Channel.EndConsultarExistenciaVenta(result);
        }
        
        private System.IAsyncResult OnBeginConsultarExistenciaVenta(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string ventas = ((string)(inValues[0]));
            return ((CYLTRACK_PHONE.VentaService.IVentaService)(this)).BeginConsultarExistenciaVenta(ventas, callback, asyncState);
        }
        
        private object[] OnEndConsultarExistenciaVenta(System.IAsyncResult result) {
            long retVal = ((CYLTRACK_PHONE.VentaService.IVentaService)(this)).EndConsultarExistenciaVenta(result);
            return new object[] {
                    retVal};
        }
        
        private void OnConsultarExistenciaVentaCompleted(object state) {
            if ((this.ConsultarExistenciaVentaCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.ConsultarExistenciaVentaCompleted(this, new ConsultarExistenciaVentaCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void ConsultarExistenciaVentaAsync(string ventas) {
            this.ConsultarExistenciaVentaAsync(ventas, null);
        }
        
        public void ConsultarExistenciaVentaAsync(string ventas, object userState) {
            if ((this.onBeginConsultarExistenciaVentaDelegate == null)) {
                this.onBeginConsultarExistenciaVentaDelegate = new BeginOperationDelegate(this.OnBeginConsultarExistenciaVenta);
            }
            if ((this.onEndConsultarExistenciaVentaDelegate == null)) {
                this.onEndConsultarExistenciaVentaDelegate = new EndOperationDelegate(this.OnEndConsultarExistenciaVenta);
            }
            if ((this.onConsultarExistenciaVentaCompletedDelegate == null)) {
                this.onConsultarExistenciaVentaCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnConsultarExistenciaVentaCompleted);
            }
            base.InvokeAsync(this.onBeginConsultarExistenciaVentaDelegate, new object[] {
                        ventas}, this.onEndConsultarExistenciaVentaDelegate, this.onConsultarExistenciaVentaCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult CYLTRACK_PHONE.VentaService.IVentaService.BeginConsultarVenta(string datoConsulta, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginConsultarVenta(datoConsulta, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CYLTRACK_PHONE.VentaService.VentaBE CYLTRACK_PHONE.VentaService.IVentaService.EndConsultarVenta(System.IAsyncResult result) {
            return base.Channel.EndConsultarVenta(result);
        }
        
        private System.IAsyncResult OnBeginConsultarVenta(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string datoConsulta = ((string)(inValues[0]));
            return ((CYLTRACK_PHONE.VentaService.IVentaService)(this)).BeginConsultarVenta(datoConsulta, callback, asyncState);
        }
        
        private object[] OnEndConsultarVenta(System.IAsyncResult result) {
            CYLTRACK_PHONE.VentaService.VentaBE retVal = ((CYLTRACK_PHONE.VentaService.IVentaService)(this)).EndConsultarVenta(result);
            return new object[] {
                    retVal};
        }
        
        private void OnConsultarVentaCompleted(object state) {
            if ((this.ConsultarVentaCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.ConsultarVentaCompleted(this, new ConsultarVentaCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void ConsultarVentaAsync(string datoConsulta) {
            this.ConsultarVentaAsync(datoConsulta, null);
        }
        
        public void ConsultarVentaAsync(string datoConsulta, object userState) {
            if ((this.onBeginConsultarVentaDelegate == null)) {
                this.onBeginConsultarVentaDelegate = new BeginOperationDelegate(this.OnBeginConsultarVenta);
            }
            if ((this.onEndConsultarVentaDelegate == null)) {
                this.onEndConsultarVentaDelegate = new EndOperationDelegate(this.OnEndConsultarVenta);
            }
            if ((this.onConsultarVentaCompletedDelegate == null)) {
                this.onConsultarVentaCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnConsultarVentaCompleted);
            }
            base.InvokeAsync(this.onBeginConsultarVentaDelegate, new object[] {
                        datoConsulta}, this.onEndConsultarVentaDelegate, this.onConsultarVentaCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult CYLTRACK_PHONE.VentaService.IVentaService.BeginRevisionCasosEspeciales(string casos, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginRevisionCasosEspeciales(casos, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Collections.ObjectModel.ObservableCollection<CYLTRACK_PHONE.VentaService.CasosBE> CYLTRACK_PHONE.VentaService.IVentaService.EndRevisionCasosEspeciales(System.IAsyncResult result) {
            return base.Channel.EndRevisionCasosEspeciales(result);
        }
        
        private System.IAsyncResult OnBeginRevisionCasosEspeciales(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string casos = ((string)(inValues[0]));
            return ((CYLTRACK_PHONE.VentaService.IVentaService)(this)).BeginRevisionCasosEspeciales(casos, callback, asyncState);
        }
        
        private object[] OnEndRevisionCasosEspeciales(System.IAsyncResult result) {
            System.Collections.ObjectModel.ObservableCollection<CYLTRACK_PHONE.VentaService.CasosBE> retVal = ((CYLTRACK_PHONE.VentaService.IVentaService)(this)).EndRevisionCasosEspeciales(result);
            return new object[] {
                    retVal};
        }
        
        private void OnRevisionCasosEspecialesCompleted(object state) {
            if ((this.RevisionCasosEspecialesCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.RevisionCasosEspecialesCompleted(this, new RevisionCasosEspecialesCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void RevisionCasosEspecialesAsync(string casos) {
            this.RevisionCasosEspecialesAsync(casos, null);
        }
        
        public void RevisionCasosEspecialesAsync(string casos, object userState) {
            if ((this.onBeginRevisionCasosEspecialesDelegate == null)) {
                this.onBeginRevisionCasosEspecialesDelegate = new BeginOperationDelegate(this.OnBeginRevisionCasosEspeciales);
            }
            if ((this.onEndRevisionCasosEspecialesDelegate == null)) {
                this.onEndRevisionCasosEspecialesDelegate = new EndOperationDelegate(this.OnEndRevisionCasosEspeciales);
            }
            if ((this.onRevisionCasosEspecialesCompletedDelegate == null)) {
                this.onRevisionCasosEspecialesCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnRevisionCasosEspecialesCompleted);
            }
            base.InvokeAsync(this.onBeginRevisionCasosEspecialesDelegate, new object[] {
                        casos}, this.onEndRevisionCasosEspecialesDelegate, this.onRevisionCasosEspecialesCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult CYLTRACK_PHONE.VentaService.IVentaService.BeginCasosEspeciales(CYLTRACK_PHONE.VentaService.CasosBE casos, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginCasosEspeciales(casos, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        long CYLTRACK_PHONE.VentaService.IVentaService.EndCasosEspeciales(System.IAsyncResult result) {
            return base.Channel.EndCasosEspeciales(result);
        }
        
        private System.IAsyncResult OnBeginCasosEspeciales(object[] inValues, System.AsyncCallback callback, object asyncState) {
            CYLTRACK_PHONE.VentaService.CasosBE casos = ((CYLTRACK_PHONE.VentaService.CasosBE)(inValues[0]));
            return ((CYLTRACK_PHONE.VentaService.IVentaService)(this)).BeginCasosEspeciales(casos, callback, asyncState);
        }
        
        private object[] OnEndCasosEspeciales(System.IAsyncResult result) {
            long retVal = ((CYLTRACK_PHONE.VentaService.IVentaService)(this)).EndCasosEspeciales(result);
            return new object[] {
                    retVal};
        }
        
        private void OnCasosEspecialesCompleted(object state) {
            if ((this.CasosEspecialesCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.CasosEspecialesCompleted(this, new CasosEspecialesCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void CasosEspecialesAsync(CYLTRACK_PHONE.VentaService.CasosBE casos) {
            this.CasosEspecialesAsync(casos, null);
        }
        
        public void CasosEspecialesAsync(CYLTRACK_PHONE.VentaService.CasosBE casos, object userState) {
            if ((this.onBeginCasosEspecialesDelegate == null)) {
                this.onBeginCasosEspecialesDelegate = new BeginOperationDelegate(this.OnBeginCasosEspeciales);
            }
            if ((this.onEndCasosEspecialesDelegate == null)) {
                this.onEndCasosEspecialesDelegate = new EndOperationDelegate(this.OnEndCasosEspeciales);
            }
            if ((this.onCasosEspecialesCompletedDelegate == null)) {
                this.onCasosEspecialesCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCasosEspecialesCompleted);
            }
            base.InvokeAsync(this.onBeginCasosEspecialesDelegate, new object[] {
                        casos}, this.onEndCasosEspecialesDelegate, this.onCasosEspecialesCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult CYLTRACK_PHONE.VentaService.IVentaService.BeginModificarVenta(CYLTRACK_PHONE.VentaService.Detalle_VentaBE detVenta, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginModificarVenta(detVenta, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        long CYLTRACK_PHONE.VentaService.IVentaService.EndModificarVenta(System.IAsyncResult result) {
            return base.Channel.EndModificarVenta(result);
        }
        
        private System.IAsyncResult OnBeginModificarVenta(object[] inValues, System.AsyncCallback callback, object asyncState) {
            CYLTRACK_PHONE.VentaService.Detalle_VentaBE detVenta = ((CYLTRACK_PHONE.VentaService.Detalle_VentaBE)(inValues[0]));
            return ((CYLTRACK_PHONE.VentaService.IVentaService)(this)).BeginModificarVenta(detVenta, callback, asyncState);
        }
        
        private object[] OnEndModificarVenta(System.IAsyncResult result) {
            long retVal = ((CYLTRACK_PHONE.VentaService.IVentaService)(this)).EndModificarVenta(result);
            return new object[] {
                    retVal};
        }
        
        private void OnModificarVentaCompleted(object state) {
            if ((this.ModificarVentaCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.ModificarVentaCompleted(this, new ModificarVentaCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void ModificarVentaAsync(CYLTRACK_PHONE.VentaService.Detalle_VentaBE detVenta) {
            this.ModificarVentaAsync(detVenta, null);
        }
        
        public void ModificarVentaAsync(CYLTRACK_PHONE.VentaService.Detalle_VentaBE detVenta, object userState) {
            if ((this.onBeginModificarVentaDelegate == null)) {
                this.onBeginModificarVentaDelegate = new BeginOperationDelegate(this.OnBeginModificarVenta);
            }
            if ((this.onEndModificarVentaDelegate == null)) {
                this.onEndModificarVentaDelegate = new EndOperationDelegate(this.OnEndModificarVenta);
            }
            if ((this.onModificarVentaCompletedDelegate == null)) {
                this.onModificarVentaCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnModificarVentaCompleted);
            }
            base.InvokeAsync(this.onBeginModificarVentaDelegate, new object[] {
                        detVenta}, this.onEndModificarVentaDelegate, this.onModificarVentaCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginOpen(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(callback, asyncState);
        }
        
        private object[] OnEndOpen(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndOpen(result);
            return null;
        }
        
        private void OnOpenCompleted(object state) {
            if ((this.OpenCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.OpenCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void OpenAsync() {
            this.OpenAsync(null);
        }
        
        public void OpenAsync(object userState) {
            if ((this.onBeginOpenDelegate == null)) {
                this.onBeginOpenDelegate = new BeginOperationDelegate(this.OnBeginOpen);
            }
            if ((this.onEndOpenDelegate == null)) {
                this.onEndOpenDelegate = new EndOperationDelegate(this.OnEndOpen);
            }
            if ((this.onOpenCompletedDelegate == null)) {
                this.onOpenCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnOpenCompleted);
            }
            base.InvokeAsync(this.onBeginOpenDelegate, null, this.onEndOpenDelegate, this.onOpenCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginClose(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginClose(callback, asyncState);
        }
        
        private object[] OnEndClose(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndClose(result);
            return null;
        }
        
        private void OnCloseCompleted(object state) {
            if ((this.CloseCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.CloseCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void CloseAsync() {
            this.CloseAsync(null);
        }
        
        public void CloseAsync(object userState) {
            if ((this.onBeginCloseDelegate == null)) {
                this.onBeginCloseDelegate = new BeginOperationDelegate(this.OnBeginClose);
            }
            if ((this.onEndCloseDelegate == null)) {
                this.onEndCloseDelegate = new EndOperationDelegate(this.OnEndClose);
            }
            if ((this.onCloseCompletedDelegate == null)) {
                this.onCloseCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCloseCompleted);
            }
            base.InvokeAsync(this.onBeginCloseDelegate, null, this.onEndCloseDelegate, this.onCloseCompletedDelegate, userState);
        }
        
        protected override CYLTRACK_PHONE.VentaService.IVentaService CreateChannel() {
            return new VentaServiceClientChannel(this);
        }
        
        private class VentaServiceClientChannel : ChannelBase<CYLTRACK_PHONE.VentaService.IVentaService>, CYLTRACK_PHONE.VentaService.IVentaService {
            
            public VentaServiceClientChannel(System.ServiceModel.ClientBase<CYLTRACK_PHONE.VentaService.IVentaService> client) : 
                    base(client) {
            }
            
            public System.IAsyncResult BeginRegistrarVenta(CYLTRACK_PHONE.VentaService.VentaBE ventas, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = ventas;
                System.IAsyncResult _result = base.BeginInvoke("RegistrarVenta", _args, callback, asyncState);
                return _result;
            }
            
            public long EndRegistrarVenta(System.IAsyncResult result) {
                object[] _args = new object[0];
                long _result = ((long)(base.EndInvoke("RegistrarVenta", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginConsultarExistenciaVenta(string ventas, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = ventas;
                System.IAsyncResult _result = base.BeginInvoke("ConsultarExistenciaVenta", _args, callback, asyncState);
                return _result;
            }
            
            public long EndConsultarExistenciaVenta(System.IAsyncResult result) {
                object[] _args = new object[0];
                long _result = ((long)(base.EndInvoke("ConsultarExistenciaVenta", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginConsultarVenta(string datoConsulta, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = datoConsulta;
                System.IAsyncResult _result = base.BeginInvoke("ConsultarVenta", _args, callback, asyncState);
                return _result;
            }
            
            public CYLTRACK_PHONE.VentaService.VentaBE EndConsultarVenta(System.IAsyncResult result) {
                object[] _args = new object[0];
                CYLTRACK_PHONE.VentaService.VentaBE _result = ((CYLTRACK_PHONE.VentaService.VentaBE)(base.EndInvoke("ConsultarVenta", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginRevisionCasosEspeciales(string casos, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = casos;
                System.IAsyncResult _result = base.BeginInvoke("RevisionCasosEspeciales", _args, callback, asyncState);
                return _result;
            }
            
            public System.Collections.ObjectModel.ObservableCollection<CYLTRACK_PHONE.VentaService.CasosBE> EndRevisionCasosEspeciales(System.IAsyncResult result) {
                object[] _args = new object[0];
                System.Collections.ObjectModel.ObservableCollection<CYLTRACK_PHONE.VentaService.CasosBE> _result = ((System.Collections.ObjectModel.ObservableCollection<CYLTRACK_PHONE.VentaService.CasosBE>)(base.EndInvoke("RevisionCasosEspeciales", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginCasosEspeciales(CYLTRACK_PHONE.VentaService.CasosBE casos, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = casos;
                System.IAsyncResult _result = base.BeginInvoke("CasosEspeciales", _args, callback, asyncState);
                return _result;
            }
            
            public long EndCasosEspeciales(System.IAsyncResult result) {
                object[] _args = new object[0];
                long _result = ((long)(base.EndInvoke("CasosEspeciales", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginModificarVenta(CYLTRACK_PHONE.VentaService.Detalle_VentaBE detVenta, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = detVenta;
                System.IAsyncResult _result = base.BeginInvoke("ModificarVenta", _args, callback, asyncState);
                return _result;
            }
            
            public long EndModificarVenta(System.IAsyncResult result) {
                object[] _args = new object[0];
                long _result = ((long)(base.EndInvoke("ModificarVenta", _args, result)));
                return _result;
            }
        }
    }
}
