//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.18444
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CYLTRACK_WebApp.RutaService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://servicios.cyltrack.com.co/cyltrack/", ConfigurationName="RutaService.IRutaServices")]
    public interface IRutaServices {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://servicios.cyltrack.com.co/cyltrack/IRutaServices/RegistrarRuta", ReplyAction="http://servicios.cyltrack.com.co/cyltrack/IRutaServices/RegistrarRutaResponse")]
        long RegistrarRuta(Unisangil.CYLTRACK.CYLTRACK_BE.RutaBE ruta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://servicios.cyltrack.com.co/cyltrack/IRutaServices/ModificarRuta", ReplyAction="http://servicios.cyltrack.com.co/cyltrack/IRutaServices/ModificarRutaResponse")]
        long ModificarRuta(Unisangil.CYLTRACK.CYLTRACK_BE.RutaBE ruta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://servicios.cyltrack.com.co/cyltrack/IRutaServices/ConsultarRuta", ReplyAction="http://servicios.cyltrack.com.co/cyltrack/IRutaServices/ConsultarRutaResponse")]
        Unisangil.CYLTRACK.CYLTRACK_BE.RutaBE[] ConsultarRuta(string ruta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://servicios.cyltrack.com.co/cyltrack/IRutaServices/ConsultarRutaPorPlaca", ReplyAction="http://servicios.cyltrack.com.co/cyltrack/IRutaServices/ConsultarRutaPorPlacaResp" +
            "onse")]
        Unisangil.CYLTRACK.CYLTRACK_BE.RutaBE ConsultarRutaPorPlaca(Unisangil.CYLTRACK.CYLTRACK_BE.Ruta_VehiculoBE rutaVehiculo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://servicios.cyltrack.com.co/cyltrack/IRutaServices/ConsultaDepartamento", ReplyAction="http://servicios.cyltrack.com.co/cyltrack/IRutaServices/ConsultaDepartamentoRespo" +
            "nse")]
        Unisangil.CYLTRACK.CYLTRACK_BE.DepartamentoBE[] ConsultaDepartamento();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://servicios.cyltrack.com.co/cyltrack/IRutaServices/ConsultaCiudades", ReplyAction="http://servicios.cyltrack.com.co/cyltrack/IRutaServices/ConsultaCiudadesResponse")]
        Unisangil.CYLTRACK.CYLTRACK_BE.CiudadBE[] ConsultaCiudades(string id_dep);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://servicios.cyltrack.com.co/cyltrack/IRutaServices/ConsultaExistenciaRuta", ReplyAction="http://servicios.cyltrack.com.co/cyltrack/IRutaServices/ConsultaExistenciaRutaRes" +
            "ponse")]
        long ConsultaExistenciaRuta(string ruta);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IRutaServicesChannel : CYLTRACK_WebApp.RutaService.IRutaServices, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RutaServicesClient : System.ServiceModel.ClientBase<CYLTRACK_WebApp.RutaService.IRutaServices>, CYLTRACK_WebApp.RutaService.IRutaServices {
        
        public RutaServicesClient() {
        }
        
        public RutaServicesClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public RutaServicesClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RutaServicesClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RutaServicesClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public long RegistrarRuta(Unisangil.CYLTRACK.CYLTRACK_BE.RutaBE ruta) {
            return base.Channel.RegistrarRuta(ruta);
        }
        
        public long ModificarRuta(Unisangil.CYLTRACK.CYLTRACK_BE.RutaBE ruta) {
            return base.Channel.ModificarRuta(ruta);
        }
        
        public Unisangil.CYLTRACK.CYLTRACK_BE.RutaBE[] ConsultarRuta(string ruta) {
            return base.Channel.ConsultarRuta(ruta);
        }
        
        public Unisangil.CYLTRACK.CYLTRACK_BE.RutaBE ConsultarRutaPorPlaca(Unisangil.CYLTRACK.CYLTRACK_BE.Ruta_VehiculoBE rutaVehiculo) {
            return base.Channel.ConsultarRutaPorPlaca(rutaVehiculo);
        }
        
        public Unisangil.CYLTRACK.CYLTRACK_BE.DepartamentoBE[] ConsultaDepartamento() {
            return base.Channel.ConsultaDepartamento();
        }
        
        public Unisangil.CYLTRACK.CYLTRACK_BE.CiudadBE[] ConsultaCiudades(string id_dep) {
            return base.Channel.ConsultaCiudades(id_dep);
        }
        
        public long ConsultaExistenciaRuta(string ruta) {
            return base.Channel.ConsultaExistenciaRuta(ruta);
        }
    }
}
