//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.235
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CYLTRACK_WebApp.CilindroService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://servicios.cyltrack.com.co/cyltrack/", ConfigurationName="CilindroService.ICilindroService")]
    public interface ICilindroService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://servicios.cyltrack.com.co/cyltrack/ICilindroService/RegistrarCilindro", ReplyAction="http://servicios.cyltrack.com.co/cyltrack/ICilindroService/RegistrarCilindroRespo" +
            "nse")]
        string RegistrarCilindro(Unisangil.CYLTRACK.CYLTRACK_BE.CilindroBE cilindro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://servicios.cyltrack.com.co/cyltrack/ICilindroService/ConsultarCilindro", ReplyAction="http://servicios.cyltrack.com.co/cyltrack/ICilindroService/ConsultarCilindroRespo" +
            "nse")]
        Unisangil.CYLTRACK.CYLTRACK_BE.CilindroBE ConsultarCilindro(string cilindro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://servicios.cyltrack.com.co/cyltrack/ICilindroService/AsignarUbicacion", ReplyAction="http://servicios.cyltrack.com.co/cyltrack/ICilindroService/AsignarUbicacionRespon" +
            "se")]
        string AsignarUbicacion(Unisangil.CYLTRACK.CYLTRACK_BE.CilindroBE cilindro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://servicios.cyltrack.com.co/cyltrack/ICilindroService/ConsultarCilUbicacion", ReplyAction="http://servicios.cyltrack.com.co/cyltrack/ICilindroService/ConsultarCilUbicacionR" +
            "esponse")]
        Unisangil.CYLTRACK.CYLTRACK_BE.CilindroBE[] ConsultarCilUbicacion(string ubicacion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://servicios.cyltrack.com.co/cyltrack/ICilindroService/CargueyDescargueCilind" +
            "ros", ReplyAction="http://servicios.cyltrack.com.co/cyltrack/ICilindroService/CargueyDescargueCilind" +
            "rosResponse")]
        string CargueyDescargueCilindros(Unisangil.CYLTRACK.CYLTRACK_BE.CilindroBE[] cilindros);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://servicios.cyltrack.com.co/cyltrack/ICilindroService/consultadeExistencia", ReplyAction="http://servicios.cyltrack.com.co/cyltrack/ICilindroService/consultadeExistenciaRe" +
            "sponse")]
        string consultadeExistencia(string cilindro);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICilindroServiceChannel : CYLTRACK_WebApp.CilindroService.ICilindroService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CilindroServiceClient : System.ServiceModel.ClientBase<CYLTRACK_WebApp.CilindroService.ICilindroService>, CYLTRACK_WebApp.CilindroService.ICilindroService {
        
        public CilindroServiceClient() {
        }
        
        public CilindroServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CilindroServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CilindroServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CilindroServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string RegistrarCilindro(Unisangil.CYLTRACK.CYLTRACK_BE.CilindroBE cilindro) {
            return base.Channel.RegistrarCilindro(cilindro);
        }
        
        public Unisangil.CYLTRACK.CYLTRACK_BE.CilindroBE ConsultarCilindro(string cilindro) {
            return base.Channel.ConsultarCilindro(cilindro);
        }
        
        public string AsignarUbicacion(Unisangil.CYLTRACK.CYLTRACK_BE.CilindroBE cilindro) {
            return base.Channel.AsignarUbicacion(cilindro);
        }
        
        public Unisangil.CYLTRACK.CYLTRACK_BE.CilindroBE[] ConsultarCilUbicacion(string ubicacion) {
            return base.Channel.ConsultarCilUbicacion(ubicacion);
        }
        
        public string CargueyDescargueCilindros(Unisangil.CYLTRACK.CYLTRACK_BE.CilindroBE[] cilindros) {
            return base.Channel.CargueyDescargueCilindros(cilindros);
        }
        
        public string consultadeExistencia(string cilindro) {
            return base.Channel.consultadeExistencia(cilindro);
        }
    }
}
